#ifndef LABAND_SNAPSHOT_RING_H
#define LABAND_SNAPSHOT_RING_H

#include <stdint.h>

enum {
    LABAND_SNAPSHOT_RING_ABI_VERSION = 1,
    LABAND_SNAPSHOT_RING_FILE_HEADER_BYTES = 64,
    LABAND_SNAPSHOT_RING_SLOT_HEADER_BYTES = 96,
    LABAND_SNAPSHOT_RING_CELL_BYTES = 32,
    LABAND_SNAPSHOT_RING_MIN_SLOT_COUNT = 3,
    LABAND_SNAPSHOT_RING_DEFAULT_SLOT_COUNT = 3,
    LABAND_SNAPSHOT_RING_BYTE_ORDER_MARKER = 0x01020304u
};

enum {
    LABAND_SNAPSHOT_RING_MAGIC_0 = 'L',
    LABAND_SNAPSHOT_RING_MAGIC_1 = 'B',
    LABAND_SNAPSHOT_RING_MAGIC_2 = 'N',
    LABAND_SNAPSHOT_RING_MAGIC_3 = 'D',
    LABAND_SNAPSHOT_RING_MAGIC_4 = 'S',
    LABAND_SNAPSHOT_RING_MAGIC_5 = 'S',
    LABAND_SNAPSHOT_RING_MAGIC_6 = '0',
    LABAND_SNAPSHOT_RING_MAGIC_7 = '1'
};

enum {
    LABAND_RING_FILE_MAGIC_OFFSET = 0,
    LABAND_RING_FILE_ABI_VERSION_OFFSET = 8,
    LABAND_RING_FILE_HEADER_BYTES_OFFSET = 10,
    LABAND_RING_FILE_SLOT_HEADER_BYTES_OFFSET = 12,
    LABAND_RING_FILE_CELL_BYTES_OFFSET = 14,
    LABAND_RING_FILE_SLOT_COUNT_OFFSET = 16,
    LABAND_RING_FILE_MAX_ROWS_OFFSET = 18,
    LABAND_RING_FILE_MAX_COLS_OFFSET = 20,
    LABAND_RING_FILE_BYTE_ORDER_MARKER_OFFSET = 24,
    LABAND_RING_FILE_SLOT_STRIDE_OFFSET = 28,
    LABAND_RING_FILE_SESSION_ID_HASH_OFFSET = 32,
    LABAND_RING_FILE_INCARNATION_ID_HASH_OFFSET = 40,
    LABAND_RING_FILE_WRITER_GENERATION_OFFSET = 48,
    LABAND_RING_FILE_FLAGS_OFFSET = 56
};

enum {
    LABAND_RING_SLOT_SEQLOCK_OFFSET = 0,
    LABAND_RING_SLOT_GENERATION_OFFSET = 8,
    LABAND_RING_SLOT_ROWS_OFFSET = 16,
    LABAND_RING_SLOT_COLS_OFFSET = 18,
    LABAND_RING_SLOT_CURSOR_ROW_OFFSET = 20,
    LABAND_RING_SLOT_CURSOR_COL_OFFSET = 22,
    LABAND_RING_SLOT_FLAGS_OFFSET = 24,
    LABAND_RING_SLOT_DIRTY_RANGE_COUNT_OFFSET = 28,
    LABAND_RING_SLOT_STRING_TABLE_BYTES_OFFSET = 32,
    LABAND_RING_SLOT_SCROLLBACK_ANCHOR_OFFSET = 40,
    LABAND_RING_SLOT_INPUT_SEQ_APPLIED_OFFSET = 48,
    LABAND_RING_SLOT_ECHO_ACK_SEQ_OFFSET = 56,
    LABAND_RING_SLOT_PTY_DRAIN_MONO_NS_OFFSET = 64,
    LABAND_RING_SLOT_SNAPSHOT_PUBLISH_MONO_NS_OFFSET = 72,
    LABAND_RING_SLOT_TITLE_GENERATION_OFFSET = 80
};

enum {
    LABAND_RING_SLOT_FLAG_ALTERNATE_SCREEN = 1u << 0,
    LABAND_RING_SLOT_FLAG_CURSOR_VISIBLE = 1u << 1,
    LABAND_RING_SLOT_FLAG_CURSOR_BLINK = 1u << 2,
    LABAND_RING_SLOT_FLAG_SYNCHRONIZED_OUTPUT = 1u << 3
};

enum {
    LABAND_RING_CELL_CODEPOINT_OFFSET = 0,
    LABAND_RING_CELL_STRING_OFFSET_OFFSET = 4,
    LABAND_RING_CELL_STRING_LENGTH_OFFSET = 8,
    LABAND_RING_CELL_WIDTH_OFFSET = 10,
    LABAND_RING_CELL_UNDERLINE_STYLE_OFFSET = 11,
    LABAND_RING_CELL_FLAGS_OFFSET = 12,
    LABAND_RING_CELL_FOREGROUND_RGBA_OFFSET = 16,
    LABAND_RING_CELL_BACKGROUND_RGBA_OFFSET = 20,
    LABAND_RING_CELL_HYPERLINK_INDEX_OFFSET = 24,
    LABAND_RING_CELL_SEMANTIC_TOKEN_INDEX_OFFSET = 28
};

#endif
