// Generated by scripts/build-app — do not edit by hand.
enum BuildInfo {
  static let commit = "557edbe+dirty"
  static let date = "2026-05-05T13:54:21Z"
  static var summary: String { "laban \(commit) (\(date))" }
}
