#!/usr/bin/env python3
"""Generate the TraceData TLA+ module from a labpty attachment trace.

The daemon's labpty_trace_emit writes one NDJSON record per attachment
transition:

    {"action": "...", "inUse": [0/1 per client],
     "alive": [0/1 per session], "attached": [[client ids] per session]}

This emits a TraceData module that specs/labpty/TraceAttachment.tla replays:

    Trace == << [inUse |-> {set}, alive |-> {set}, attached |-> <fn>], ... >>

with inUse/alive as sets of live indices and attached as a function from
session id to the set of attached client ids (empty sessions omitted).

Usage: gen-trace-tla.py <trace.ndjson> [out.tla]   (default: stdout)
"""
import json
import sys


def tla_set(ids):
    return "{" + ", ".join(str(i) for i in ids) + "}"


def tla_attached(attached):
    parts = [(s, lst) for s, lst in enumerate(attached) if lst]
    if not parts:
        # Empty-domain function: no session carries an attachment.
        return "[s \\in {} |-> {}]"
    return "(" + " @@ ".join(f"{s} :> {tla_set(lst)}" for s, lst in parts) + ")"


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen-trace-tla.py <trace.ndjson> [out.tla]")
    records = []
    with open(sys.argv[1]) as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    if not records:
        sys.exit("gen-trace-tla.py: trace is empty")

    n_clients = len(records[0]["inUse"])
    n_sessions = len(records[0]["alive"])

    rows = []
    for r in records:
        inuse = tla_set([c for c, v in enumerate(r["inUse"]) if v])
        alive = tla_set([s for s, v in enumerate(r["alive"]) if v])
        att = tla_attached(r["attached"])
        rows.append(
            f"    [inUse |-> {inuse}, alive |-> {alive}, attached |-> {att}]"
        )

    out = []
    out.append("------------------------------ MODULE TraceData ------------------------------")
    out.append("\\* GENERATED by scripts/gen-trace-tla.py from a labpty attachment trace.")
    out.append("\\* Do not edit; regenerated on every scripts/check-trace run.")
    out.append("EXTENDS TLC, Naturals")
    out.append("")
    out.append(f"TraceClients  == 0..{n_clients - 1}")
    out.append(f"TraceSessions == 0..{n_sessions - 1}")
    out.append("")
    out.append("Trace == <<")
    out.append(",\n".join(rows))
    out.append(">>")
    out.append("")
    out.append("=============================================================================")
    text = "\n".join(out) + "\n"

    if len(sys.argv) >= 3:
        with open(sys.argv[2], "w") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
