#!/usr/bin/env python3
"""Generate Sources/LabanApp/Resources/Localizable.xcstrings from the translation table."""

from __future__ import annotations

import json
import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "Sources/LabanApp/Resources/Localizable.xcstrings"

LOCALES = ("zh-Hans", "zh-Hant", "ja", "ko", "fr", "es", "hi", "ru", "de", "pt-BR", "it")

from importlib.machinery import SourceFileLoader

_supplement_mod = SourceFileLoader(
    "localizable_supplement",
    str(REPO / "scripts/localizable-supplement-de-pt-it.py"),
).load_module()
SUPPLEMENT_DE_PT_IT: dict[str, dict[str, str]] = _supplement_mod.SUPPLEMENT_DE_PT_IT

FOCUS_STATUS_USAGE_DESCRIPTION = (
    "Laban checks whether an active Focus is silencing terminal-attention notifications "
    "when you explicitly run Focus troubleshooting."
)

# English source -> per-locale translations. Keep keys identical to Swift L10n.tr("…") calls.
TRANSLATIONS: dict[str, dict[str, str]] = {
    # App menu
    "About Laban": {
        "zh-Hans": "关于 Laban",
        "zh-Hant": "關於 Laban",
        "ja": "Laban について",
        "ko": "Laban 정보",
        "fr": "À propos de Laban",
        "es": "Acerca de Laban",
        "hi": "Laban के बारे में",
        "ru": "О программе Laban",
    },
    "Check for Updates…": {
        "zh-Hans": "检查更新…",
        "zh-Hant": "檢查更新…",
        "ja": "アップデートを確認…",
        "ko": "업데이트 확인…",
        "fr": "Rechercher des mises à jour…",
        "es": "Buscar actualizaciones…",
        "hi": "अपडेट जाँचें…",
        "ru": "Проверить обновления…",
    },
    "Settings…": {
        "zh-Hans": "设置…",
        "zh-Hant": "設定…",
        "ja": "設定…",
        "ko": "설정…",
        "fr": "Réglages…",
        "es": "Ajustes…",
        "hi": "सेटिंग्स…",
        "ru": "Настройки…",
    },
    "Secure Keyboard Entry": {
        "zh-Hans": "安全键盘输入",
        "zh-Hant": "安全鍵盤輸入",
        "ja": "セキュアキーボード入力",
        "ko": "보안 키보드 입력",
        "fr": "Saisie clavier sécurisée",
        "es": "Entrada de teclado segura",
        "hi": "सुरक्षित कीबोर्ड इनपुट",
        "ru": "Безопасный ввод с клавиатуры",
    },
    "Hide Laban": {
        "zh-Hans": "隐藏 Laban",
        "zh-Hant": "隱藏 Laban",
        "ja": "Laban を隠す",
        "ko": "Laban 숨기기",
        "fr": "Masquer Laban",
        "es": "Ocultar Laban",
        "hi": "Laban छुपाएँ",
        "ru": "Скрыть Laban",
    },
    "Hide Others": {
        "zh-Hans": "隐藏其他",
        "zh-Hant": "隱藏其他",
        "ja": "ほかを隠す",
        "ko": "기타 항목 숨기기",
        "fr": "Masquer les autres",
        "es": "Ocultar otros",
        "hi": "अन्य छुपाएँ",
        "ru": "Скрыть остальные",
    },
    "Show All": {
        "zh-Hans": "全部显示",
        "zh-Hant": "顯示全部",
        "ja": "すべてを表示",
        "ko": "모두 보기",
        "fr": "Tout afficher",
        "es": "Mostrar todo",
        "hi": "सभी दिखाएँ",
        "ru": "Показать все",
    },
    "Restart Laban": {
        "zh-Hans": "重新启动 Laban",
        "zh-Hant": "重新啟動 Laban",
        "ja": "Laban を再起動",
        "ko": "Laban 다시 시작",
        "fr": "Redémarrer Laban",
        "es": "Reiniciar Laban",
        "hi": "Laban पुनः प्रारंभ करें",
        "ru": "Перезапустить Laban",
    },
    "Quit Laban": {
        "zh-Hans": "退出 Laban",
        "zh-Hant": "結束 Laban",
        "ja": "Laban を終了",
        "ko": "Laban 종료",
        "fr": "Quitter Laban",
        "es": "Salir de Laban",
        "hi": "Laban बंद करें",
        "ru": "Выйти из Laban",
    },
    "File": {
        "zh-Hans": "文件",
        "zh-Hant": "檔案",
        "ja": "ファイル",
        "ko": "파일",
        "fr": "Fichier",
        "es": "Archivo",
        "hi": "फ़ाइल",
        "ru": "Файл",
    },
    "New Tab": {
        "zh-Hans": "新建标签页",
        "zh-Hant": "新增標籤頁",
        "ja": "新しいタブ",
        "ko": "새 탭",
        "fr": "Nouvel onglet",
        "es": "Nueva pestaña",
        "hi": "नया टैब",
        "ru": "Новая вкладка",
    },
    "Close Tab": {
        "zh-Hans": "关闭标签页",
        "zh-Hant": "關閉標籤頁",
        "ja": "タブを閉じる",
        "ko": "탭 닫기",
        "fr": "Fermer l’onglet",
        "es": "Cerrar pestaña",
        "hi": "टैब बंद करें",
        "ru": "Закрыть вкладку",
    },
    "Export Last 10 s as Cast": {
        "zh-Hans": "导出最近 10 秒为 Cast",
        "zh-Hant": "匯出最近 10 秒為 Cast",
        "ja": "直近 10 秒を Cast として書き出す",
        "ko": "최근 10초를 Cast로보내기",
        "fr": "Exporter les 10 dernières s en Cast",
        "es": "Exportar los últimos 10 s como Cast",
        "hi": "पिछले 10 सेकंड Cast के रूप में निर्यात करें",
        "ru": "Экспортировать последние 10 с в Cast",
    },
    "Export Recent…": {
        "zh-Hans": "导出最近记录…",
        "zh-Hant": "匯出最近記錄…",
        "ja": "最近の記録を書き出す…",
        "ko": "최근 기록보내기…",
        "fr": "Exporter l’historique récent…",
        "es": "Exportar reciente…",
        "hi": "हालिया निर्यात करें…",
        "ru": "Экспортировать недавнее…",
    },
    "Last 5 s as Cast": {
        "zh-Hans": "最近 5 秒 Cast",
        "zh-Hant": "最近 5 秒 Cast",
        "ja": "直近 5 秒を Cast",
        "ko": "최근 5초 Cast",
        "fr": "5 dernières s en Cast",
        "es": "Últimos 5 s como Cast",
        "hi": "पिछले 5 सेकंड Cast",
        "ru": "Последние 5 с в Cast",
    },
    "Last 10 s as Cast": {
        "zh-Hans": "最近 10 秒 Cast",
        "zh-Hant": "最近 10 秒 Cast",
        "ja": "直近 10 秒を Cast",
        "ko": "최근 10초 Cast",
        "fr": "10 dernières s en Cast",
        "es": "Últimos 10 s como Cast",
        "hi": "पिछले 10 सेकंड Cast",
        "ru": "Последние 10 с в Cast",
    },
    "Last 30 s as Cast": {
        "zh-Hans": "最近 30 秒 Cast",
        "zh-Hant": "最近 30 秒 Cast",
        "ja": "直近 30 秒を Cast",
        "ko": "최근 30초 Cast",
        "fr": "30 dernières s en Cast",
        "es": "Últimos 30 s como Cast",
        "hi": "पिछले 30 सेकंड Cast",
        "ru": "Последние 30 с в Cast",
    },
    "Last 60 s as Cast": {
        "zh-Hans": "最近 60 秒 Cast",
        "zh-Hant": "最近 60 秒 Cast",
        "ja": "直近 60 秒を Cast",
        "ko": "최근 60초 Cast",
        "fr": "60 dernières s en Cast",
        "es": "Últimos 60 s como Cast",
        "hi": "पिछले 60 सेकंड Cast",
        "ru": "Последние 60 с в Cast",
    },
    "Edit": {
        "zh-Hans": "编辑",
        "zh-Hant": "編輯",
        "ja": "編集",
        "ko": "편집",
        "fr": "Édition",
        "es": "Edición",
        "hi": "संपादन",
        "ru": "Правка",
    },
    "Copy": {
        "zh-Hans": "复制",
        "zh-Hant": "複製",
        "ja": "コピー",
        "ko": "복사",
        "fr": "Copier",
        "es": "Copiar",
        "hi": "कॉपी करें",
        "ru": "Копировать",
    },
    "Paste": {
        "zh-Hans": "粘贴",
        "zh-Hant": "貼上",
        "ja": "ペースト",
        "ko": "붙여넣기",
        "fr": "Coller",
        "es": "Pegar",
        "hi": "पेस्ट करें",
        "ru": "Вставить",
    },
    "Select All": {
        "zh-Hans": "全选",
        "zh-Hant": "全選",
        "ja": "すべてを選択",
        "ko": "모두 선택",
        "fr": "Tout sélectionner",
        "es": "Seleccionar todo",
        "hi": "सभी चुनें",
        "ru": "Выбрать все",
    },
    "Quick Look": {
        "zh-Hans": "快速查看",
        "zh-Hant": "快速預覽",
        "ja": "クイックルック",
        "ko": "빠른 보기",
        "fr": "Coup d’œil",
        "es": "Vista rápida",
        "hi": "त्वरित देखें",
        "ru": "Быстрый просмотр",
    },
    "Find…": {
        "zh-Hans": "查找…",
        "zh-Hant": "尋找…",
        "ja": "検索…",
        "ko": "찾기…",
        "fr": "Rechercher…",
        "es": "Buscar…",
        "hi": "खोजें…",
        "ru": "Найти…",
    },
    "View": {
        "zh-Hans": "显示",
        "zh-Hant": "顯示",
        "ja": "表示",
        "ko": "보기",
        "fr": "Présentation",
        "es": "Ver",
        "hi": "दृश्य",
        "ru": "Вид",
    },
    "Bigger Text": {
        "zh-Hans": "放大文字",
        "zh-Hant": "放大文字",
        "ja": "文字を大きく",
        "ko": "글자 크게",
        "fr": "Texte plus grand",
        "es": "Texto más grande",
        "hi": "बड़ा टेक्स्ट",
        "ru": "Увеличить текст",
    },
    "Smaller Text": {
        "zh-Hans": "缩小文字",
        "zh-Hant": "縮小文字",
        "ja": "文字を小さく",
        "ko": "글자 작게",
        "fr": "Texte plus petit",
        "es": "Texto más pequeño",
        "hi": "छोटा टेक्स्ट",
        "ru": "Уменьшить текст",
    },
    "Default Text Size": {
        "zh-Hans": "默认文字大小",
        "zh-Hant": "預設文字大小",
        "ja": "標準の文字サイズ",
        "ko": "기본 글자 크기",
        "fr": "Taille de texte par défaut",
        "es": "Tamaño de texto predeterminado",
        "hi": "डिफ़ॉल्ट टेक्स्ट आकार",
        "ru": "Размер текста по умолчанию",
    },
    "Enter Full Screen": {
        "zh-Hans": "进入全屏幕",
        "zh-Hant": "進入全螢幕",
        "ja": "フルスクリーンにする",
        "ko": "전체 화면 사용",
        "fr": "Passer en plein écran",
        "es": "Pantalla completa",
        "hi": "पूर्ण स्क्रीन में जाएँ",
        "ru": "Войти в полноэкранный режим",
    },
    "Tab": {
        "zh-Hans": "标签页",
        "zh-Hant": "標籤頁",
        "ja": "タブ",
        "ko": "탭",
        "fr": "Onglet",
        "es": "Pestaña",
        "hi": "टैब",
        "ru": "Вкладка",
    },
    "Previous Tab": {
        "zh-Hans": "上一个标签页",
        "zh-Hant": "上一個標籤頁",
        "ja": "前のタブ",
        "ko": "이전 탭",
        "fr": "Onglet précédent",
        "es": "Pestaña anterior",
        "hi": "पिछला टैब",
        "ru": "Предыдущая вкладка",
    },
    "Next Tab": {
        "zh-Hans": "下一个标签页",
        "zh-Hant": "下一個標籤頁",
        "ja": "次のタブ",
        "ko": "다음 탭",
        "fr": "Onglet suivant",
        "es": "Pestaña siguiente",
        "hi": "अगला टैब",
        "ru": "Следующая вкладка",
    },
    "Select Tab %lld": {
        "zh-Hans": "选择标签页 %lld",
        "zh-Hant": "選擇標籤頁 %lld",
        "ja": "タブ %lld を選択",
        "ko": "탭 %lld 선택",
        "fr": "Sélectionner l’onglet %lld",
        "es": "Seleccionar pestaña %lld",
        "hi": "टैब %lld चुनें",
        "ru": "Выбрать вкладку %lld",
    },
    "Select Last Tab": {
        "zh-Hans": "选择最后一个标签页",
        "zh-Hant": "選擇最後一個標籤頁",
        "ja": "最後のタブを選択",
        "ko": "마지막 탭 선택",
        "fr": "Sélectionner le dernier onglet",
        "es": "Seleccionar última pestaña",
        "hi": "अंतिम टैब चुनें",
        "ru": "Выбрать последнюю вкладку",
    },
    "Debug": {
        "zh-Hans": "调试",
        "zh-Hant": "除錯",
        "ja": "デバッグ",
        "ko": "디버그",
        "fr": "Débogage",
        "es": "Depuración",
        "hi": "डिबग",
        "ru": "Отладка",
    },
    "Start PTY Capture": {
        "zh-Hans": "开始 PTY 捕获",
        "zh-Hant": "開始 PTY 擷取",
        "ja": "PTY キャプチャを開始",
        "ko": "PTY 캡처 시작",
        "fr": "Démarrer la capture PTY",
        "es": "Iniciar captura PTY",
        "hi": "PTY कैप्चर शुरू करें",
        "ru": "Начать захват PTY",
    },
    "Stop PTY Capture": {
        "zh-Hans": "停止 PTY 捕获",
        "zh-Hant": "停止 PTY 擷取",
        "ja": "PTY キャプチャを停止",
        "ko": "PTY 캡처 중지",
        "fr": "Arrêter la capture PTY",
        "es": "Detener captura PTY",
        "hi": "PTY कैप्चर रोकें",
        "ru": "Остановить захват PTY",
    },
    "Dump Render Journal": {
        "zh-Hans": "转储渲染日志",
        "zh-Hant": "傾印渲染日誌",
        "ja": "レンダージャーナルを書き出す",
        "ko": "렌더 저널 덤프",
        "fr": "Exporter le journal de rendu",
        "es": "Volcar diario de renderizado",
        "hi": "रेंडर जर्नल डंप करें",
        "ru": "Сбросить журнал рендеринга",
    },
    "Dump Tab Journal": {
        "zh-Hans": "转储标签页日志",
        "zh-Hant": "傾印標籤頁日誌",
        "ja": "タブジャーナルを書き出す",
        "ko": "탭 저널 덤프",
        "fr": "Exporter le journal d’onglet",
        "es": "Volcar diario de pestaña",
        "hi": "टैब जर्नल डंप करें",
        "ru": "Сбросить журнал вкладки",
    },
    "Capture CPU Profile…": {
        "zh-Hans": "捕获 CPU 配置文件…",
        "zh-Hant": "擷取 CPU 設定檔…",
        "ja": "CPU プロファイルを取得…",
        "ko": "CPU 프로파일 캡처…",
        "fr": "Capturer le profil CPU…",
        "es": "Capturar perfil de CPU…",
        "hi": "CPU प्रोफ़ाइल कैप्चर करें…",
        "ru": "Снять профиль CPU…",
    },
    "Start CPU Recording": {
        "zh-Hans": "开始 CPU 录制",
        "zh-Hant": "開始 CPU 錄製",
        "ja": "CPU 記録を開始",
        "ko": "CPU 녹화 시작",
        "fr": "Démarrer l’enregistrement CPU",
        "es": "Iniciar grabación de CPU",
        "hi": "CPU रिकॉर्डिंग शुरू करें",
        "ru": "Начать запись CPU",
    },
    "Stop CPU Recording": {
        "zh-Hans": "停止 CPU 录制",
        "zh-Hant": "停止 CPU 錄製",
        "ja": "CPU 記録を停止",
        "ko": "CPU 녹화 중지",
        "fr": "Arrêter l’enregistrement CPU",
        "es": "Detener grabación de CPU",
        "hi": "CPU रिकॉर्डिंग रोकें",
        "ru": "Остановить запись CPU",
    },
    "Export CPU Profile…": {
        "zh-Hans": "导出 CPU 配置文件…",
        "zh-Hant": "匯出 CPU 設定檔…",
        "ja": "CPU プロファイルを書き出す…",
        "ko": "CPU 프로파일보내기…",
        "fr": "Exporter le profil CPU…",
        "es": "Exportar perfil de CPU…",
        "hi": "CPU प्रोफ़ाइल निर्यात करें…",
        "ru": "Экспортировать профиль CPU…",
    },
    "Send Diagnostics…": {
        "zh-Hans": "发送诊断信息…",
        "zh-Hant": "傳送診斷資訊…",
        "ja": "診断情報を送信…",
        "ko": "진단 정보 보내기…",
        "fr": "Envoyer les diagnostics…",
        "es": "Enviar diagnósticos…",
        "hi": "डायग्नोस्टिक भेजें…",
        "ru": "Отправить диагностику…",
    },
    "Window": {
        "zh-Hans": "窗口",
        "zh-Hant": "視窗",
        "ja": "ウインドウ",
        "ko": "윈도우",
        "fr": "Fenêtre",
        "es": "Ventana",
        "hi": "विंडो",
        "ru": "Окно",
    },
    "Minimize": {
        "zh-Hans": "最小化",
        "zh-Hant": "最小化",
        "ja": "しまう",
        "ko": "축소",
        "fr": "Réduire",
        "es": "Minimizar",
        "hi": "छोटा करें",
        "ru": "Свернуть",
    },
    "Zoom": {
        "zh-Hans": "缩放",
        "zh-Hant": "縮放",
        "ja": "ズーム",
        "ko": "확대/축소",
        "fr": "Zoom",
        "es": "Zoom",
        "hi": "ज़ूम",
        "ru": "Масштаб",
    },
    "Bring All to Front": {
        "zh-Hans": "全部置于前台",
        "zh-Hant": "全部移至最前",
        "ja": "すべてを前面に移動",
        "ko": "모두 앞으로 가져오기",
        "fr": "Tout ramener au premier plan",
        "es": "Traer todo al frente",
        "hi": "सभी को सामने लाएँ",
        "ru": "Вывести все на передний план",
    },
    "Help": {
        "zh-Hans": "帮助",
        "zh-Hant": "輔助說明",
        "ja": "ヘルプ",
        "ko": "도움말",
        "fr": "Aide",
        "es": "Ayuda",
        "hi": "सहायता",
        "ru": "Справка",
    },
    "Reveal Log Folder in Finder": {
        "zh-Hans": "在 Finder 中显示日志文件夹",
        "zh-Hant": "在 Finder 中顯示日誌資料夾",
        "ja": "Finder でログフォルダを表示",
        "ko": "Finder에서 로그 폴더 보기",
        "fr": "Afficher le dossier des journaux dans le Finder",
        "es": "Mostrar carpeta de registros en Finder",
        "hi": "Finder में लॉग फ़ोल्डर दिखाएँ",
        "ru": "Показать папку журналов в Finder",
    },
    # Renderer / backend menus
    "Renderer": {
        "zh-Hans": "渲染器",
        "zh-Hant": "渲染器",
        "ja": "レンダラー",
        "ko": "렌더러",
        "fr": "Moteur de rendu",
        "es": "Motor de renderizado",
        "hi": "रेंडरर",
        "ru": "Рендерер",
    },
    "Software Renderer": {
        "zh-Hans": "软件渲染器",
        "zh-Hant": "軟體渲染器",
        "ja": "ソフトウェアレンダラー",
        "ko": "소프트웨어 렌더러",
        "fr": "Rendu logiciel",
        "es": "Renderizado por software",
        "hi": "सॉफ़्टवेयर रेंडरर",
        "ru": "Программный рендерер",
    },
    "Classic Metal Renderer": {
        "zh-Hans": "经典 Metal 渲染器",
        "zh-Hant": "經典 Metal 渲染器",
        "ja": "クラシック Metal レンダラー",
        "ko": "클래식 Metal 렌더러",
        "fr": "Rendu Metal classique",
        "es": "Renderizado Metal clásico",
        "hi": "क्लासिक Metal रेंडरर",
        "ru": "Классический Metal-рендерер",
    },
    "GPU-driven Renderer": {
        "zh-Hans": "GPU 驱动渲染器",
        "zh-Hant": "GPU 驅動渲染器",
        "ja": "GPU 駆動レンダラー",
        "ko": "GPU 기반 렌더러",
        "fr": "Rendu piloté par GPU",
        "es": "Renderizado por GPU",
        "hi": "GPU-संचालित रेंडरर",
        "ru": "GPU-рендерер",
    },
    "GPU-driven Renderer (requires macOS 26)": {
        "zh-Hans": "GPU 驱动渲染器（需要 macOS 26）",
        "zh-Hant": "GPU 驅動渲染器（需要 macOS 26）",
        "ja": "GPU 駆動レンダラー（macOS 26 が必要）",
        "ko": "GPU 기반 렌더러(macOS 26 필요)",
        "fr": "Rendu piloté par GPU (macOS 26 requis)",
        "es": "Renderizado por GPU (requiere macOS 26)",
        "hi": "GPU-संचालित रेंडरर (macOS 26 आवश्यक)",
        "ru": "GPU-рендерер (требуется macOS 26)",
    },
    "Vector Glyph Renderer": {
        "zh-Hans": "矢量字形渲染器",
        "zh-Hant": "向量字形渲染器",
        "ja": "ベクターグリフレンダラー",
        "ko": "벡터 글리프 렌더러",
        "fr": "Rendu Vector Glyph",
        "es": "Renderizado Vector Glyph",
        "hi": "वेक्टर ग्लिफ़ रेंडरर",
        "ru": "Векторный глиф-рендерер",
    },
    "Slug Glyph Renderer": {
        "zh-Hans": "Slug 字形渲染器",
        "zh-Hant": "Slug 字形渲染器",
        "ja": "Slug グリフレンダラー",
        "ko": "Slug 글리프 렌더러",
        "fr": "Rendu Slug Glyph",
        "es": "Renderizado Slug Glyph",
        "hi": "Slug ग्लिफ़ रेंडरर",
        "ru": "Slug глиф-рендерер",
    },
    "Terminal Sessions": {
        "zh-Hans": "终端会话",
        "zh-Hant": "終端機工作階段",
        "ja": "ターミナルセッション",
        "ko": "터미널 세션",
        "fr": "Sessions de terminal",
        "es": "Sesiones de terminal",
        "hi": "टर्मिनल सत्र",
        "ru": "Сеансы терминала",
    },
    "Local Sessions": {
        "zh-Hans": "本地会话",
        "zh-Hant": "本機工作階段",
        "ja": "ローカルセッション",
        "ko": "로컬 세션",
        "fr": "Sessions locales",
        "es": "Sesiones locales",
        "hi": "स्थानीय सत्र",
        "ru": "Локальные сеансы",
    },
    "Background Sessions": {
        "zh-Hans": "后台会话",
        "zh-Hant": "背景工作階段",
        "ja": "バックグラウンドセッション",
        "ko": "백그라운드 세션",
        "fr": "Sessions en arrière-plan",
        "es": "Sesiones en segundo plano",
        "hi": "पृष्ठभूमि सत्र",
        "ru": "Фоновые сеансы",
    },
    "Detached Sessions": {
        "zh-Hans": "独立会话",
        "zh-Hant": "獨立工作階段",
        "ja": "デタッチセッション",
        "ko": "분리 세션",
        "fr": "Sessions détachées",
        "es": "Sesiones independientes",
        "hi": "अलग सत्र",
        "ru": "Отдельные сеансы",
    },
    "Follow System Appearance": {
        "zh-Hans": "跟随系统外观",
        "zh-Hant": "跟隨系統外觀",
        "ja": "システムの外観に合わせる",
        "ko": "시스템 모양 따르기",
        "fr": "Suivre l’apparence du système",
        "es": "Seguir apariencia del sistema",
        "hi": "सिस्टम दिखावट का पालन करें",
        "ru": "Следовать системной теме",
    },
    # Settings window
    "Laban Settings": {
        "zh-Hans": "Laban 设置",
        "zh-Hant": "Laban 設定",
        "ja": "Laban 設定",
        "ko": "Laban 설정",
        "fr": "Réglages de Laban",
        "es": "Ajustes de Laban",
        "hi": "Laban सेटिंग्स",
        "ru": "Настройки Laban",
    },
    "Follow system appearance": {
        "zh-Hans": "跟随系统外观",
        "zh-Hant": "跟隨系統外觀",
        "ja": "システムの外観に合わせる",
        "ko": "시스템 모양 따르기",
        "fr": "Suivre l’apparence du système",
        "es": "Seguir apariencia del sistema",
        "hi": "सिस्टम दिखावट का पालन करें",
        "ru": "Следовать системной теме",
    },
    "Apply": {
        "zh-Hans": "应用",
        "zh-Hant": "套用",
        "ja": "適用",
        "ko": "적용",
        "fr": "Appliquer",
        "es": "Aplicar",
        "hi": "लागू करें",
        "ru": "Применить",
    },
    "Change…": {
        "zh-Hans": "更改…",
        "zh-Hant": "更改…",
        "ja": "変更…",
        "ko": "변경…",
        "fr": "Modifier…",
        "es": "Cambiar…",
        "hi": "बदलें…",
        "ru": "Изменить…",
    },
    "Choose…": {
        "zh-Hans": "选择…",
        "zh-Hant": "選擇…",
        "ja": "選択…",
        "ko": "선택…",
        "fr": "Choisir…",
        "es": "Elegir…",
        "hi": "चुनें…",
        "ru": "Выбрать…",
    },
    "Restore tabs on launch": {
        "zh-Hans": "启动时恢复标签页",
        "zh-Hant": "啟動時恢復標籤頁",
        "ja": "起動時にタブを復元",
        "ko": "실행 시 탭 복원",
        "fr": "Restaurer les onglets au lancement",
        "es": "Restaurar pestañas al iniciar",
        "hi": "लॉन्च पर टैब पुनर्स्थापित करें",
        "ru": "Восстанавливать вкладки при запуске",
    },
    "Option as Meta": {
        "zh-Hans": "Option 作为 Meta",
        "zh-Hant": "Option 作為 Meta",
        "ja": "Option を Meta として送信",
        "ko": "Option을 Meta로 사용",
        "fr": "Option comme Meta",
        "es": "Option como Meta",
        "hi": "Option को Meta के रूप में",
        "ru": "Option как Meta",
    },
    "Notify when a tab needs action": {
        "zh-Hans": "标签页需要操作时通知",
        "zh-Hant": "標籤頁需要操作時通知",
        "ja": "タブで操作が必要なときに通知",
        "ko": "탭에 조치가 필요할 때 알림",
        "fr": "Notifier quand un onglet requiert une action",
        "es": "Notificar cuando una pestaña requiere acción",
        "hi": "जब टैब को कार्रवाई चाहिए तो सूचित करें",
        "ru": "Уведомлять, когда вкладке нужно действие",
    },
    "Notify when a task completes": {
        "zh-Hans": "任务完成时通知",
        "zh-Hant": "任務完成時通知",
        "ja": "タスク完了時に通知",
        "ko": "작업 완료 시 알림",
        "fr": "Notifier à la fin d’une tâche",
        "es": "Notificar al completar una tarea",
        "hi": "कार्य पूर्ण होने पर सूचित करें",
        "ru": "Уведомлять о завершении задачи",
    },
    "Notify for passive tab attention": {
        "zh-Hans": "被动标签页提醒时通知",
        "zh-Hant": "被動標籤頁提醒時通知",
        "ja": "低優先度のタブ注意を通知",
        "ko": "수동 탭 주의 알림",
        "fr": "Notifier l’attention passive d’un onglet",
        "es": "Notificar atención pasiva de pestaña",
        "hi": "निष्क्रिय टैब ध्यान के लिए सूचित करें",
        "ru": "Уведомлять о пассивном внимании вкладки",
    },
    "Play notification sound": {
        "zh-Hans": "播放通知声音",
        "zh-Hant": "播放通知聲音",
        "ja": "通知音を再生",
        "ko": "알림 소리 재생",
        "fr": "Jouer un son de notification",
        "es": "Reproducir sonido de notificación",
        "hi": "सूचना ध्वनि बजाएँ",
        "ru": "Воспроизводить звук уведомления",
    },
    "Test Native Notification": {
        "zh-Hans": "测试原生通知",
        "zh-Hant": "測試原生通知",
        "ja": "ネイティブ通知をテスト",
        "ko": "네이티브 알림 테스트",
        "fr": "Tester la notification native",
        "es": "Probar notificación nativa",
        "hi": "मूल सूचना परीक्षण",
        "ru": "Тест нативного уведомления",
    },
    "Blink cursor": {
        "zh-Hans": "光标闪烁",
        "zh-Hant": "游標閃爍",
        "ja": "カーソルを点滅",
        "ko": "커서 깜빡임",
        "fr": "Curseur clignotant",
        "es": "Cursor parpadeante",
        "hi": "कर्सर ब्लिंक करें",
        "ru": "Мигающий курсор",
    },
    "Enable sampling profiler (applies on next launch)": {
        "zh-Hans": "启用采样分析器（下次启动时生效）",
        "zh-Hant": "啟用取樣分析器（下次啟動時生效）",
        "ja": "サンプリングプロファイラを有効化（次回起動時に適用）",
        "ko": "샘플링 프로파일러 사용(다음 실행 시 적용)",
        "fr": "Activer le profileur d’échantillonnage (au prochain lancement)",
        "es": "Activar perfilador de muestreo (al próximo inicio)",
        "hi": "सैंपलिंग प्रोफ़ाइलर सक्षम करें (अगले लॉन्च पर लागू)",
        "ru": "Включить профилировщик выборки (при следующем запуске)",
    },
    "Appearance": {
        "zh-Hans": "外观",
        "zh-Hant": "外觀",
        "ja": "外観",
        "ko": "모양",
        "fr": "Apparence",
        "es": "Apariencia",
        "hi": "दिखावट",
        "ru": "Внешний вид",
    },
    # Terminal background transparency
    "Background opacity:": {
        "zh-Hans": "背景不透明度：",
        "zh-Hant": "背景不透明度：",
        "ja": "背景の不透明度：",
        "ko": "배경 불투명도:",
        "fr": "Opacité de l’arrière-plan :",
        "es": "Opacidad del fondo:",
        "hi": "पृष्ठभूमि अपारदर्शिता:",
        "ru": "Непрозрачность фона:",
    },
    "Background opacity": {
        "zh-Hans": "背景不透明度",
        "zh-Hant": "背景不透明度",
        "ja": "背景の不透明度",
        "ko": "배경 불투명도",
        "fr": "Opacité de l’arrière-plan",
        "es": "Opacidad del fondo",
        "hi": "पृष्ठभूमि अपारदर्शिता",
        "ru": "Непрозрачность фона",
    },
    "Background opacity: %lld percent": {
        "zh-Hans": "背景不透明度：%lld%%",
        "zh-Hant": "背景不透明度：%lld%%",
        "ja": "背景の不透明度：%lld%%",
        "ko": "배경 불투명도: %lld%%",
        "fr": "Opacité de l’arrière-plan : %lld %%",
        "es": "Opacidad del fondo: %lld %%",
        "hi": "पृष्ठभूमि अपारदर्शिता: %lld प्रतिशत",
        "ru": "Непрозрачность фона: %lld %%",
    },
    "Choose how much of the default terminal background is visible. The sidebar remains opaque; text, the cursor, selections, and images remain fully visible. 100% is fully opaque.": {
        "zh-Hans": "选择默认终端背景的可见程度。侧边栏保持不透明；文字、光标、选择区域和图像始终完全可见。100% 表示完全不透明。",
        "zh-Hant": "選擇預設終端機背景的可見程度。側邊欄保持不透明；文字、游標、選取範圍和影像始終完全可見。100% 表示完全不透明。",
        "ja": "デフォルトのターミナル背景の見え方を調整します。サイドバーは不透明のままで、テキスト、カーソル、選択範囲、画像は常に完全に表示されます。100% で完全に不透明になります。",
        "ko": "기본 터미널 배경의 표시 정도를 선택합니다. 사이드바는 불투명하게 유지되며 텍스트, 커서, 선택 영역 및 이미지는 항상 완전히 표시됩니다. 100%는 완전 불투명입니다.",
        "fr": "Réglez la visibilité de l’arrière-plan par défaut du terminal. La barre latérale reste opaque ; le texte, le curseur, les sélections et les images restent entièrement visibles. 100 % correspond à une opacité totale.",
        "es": "Elige la visibilidad del fondo predeterminado del terminal. La barra lateral permanece opaca; el texto, el cursor, las selecciones y las imágenes permanecen completamente visibles. 100 % es totalmente opaco.",
        "hi": "चुनें कि डिफ़ॉल्ट टर्मिनल की पृष्ठभूमि कितनी दिखाई दे। साइडबार अपारदर्शी रहता है; टेक्स्ट, कर्सर, चयन और चित्र पूरी तरह दिखाई देते रहते हैं। 100% पूरी तरह अपारदर्शी है।",
        "ru": "Настройте видимость фона терминала по умолчанию. Боковая панель остается непрозрачной; текст, курсор, выделение и изображения остаются полностью видимыми. 100 % означает полную непрозрачность.",
    },
    "Apply opacity to colored cell backgrounds": {
        "zh-Hans": "将不透明度应用于彩色单元格背景",
        "zh-Hant": "將不透明度套用至彩色單元格背景",
        "ja": "色付きセルの背景にも不透明度を適用",
        "ko": "색이 지정된 셀 배경에도 불투명도 적용",
        "fr": "Appliquer l’opacité aux arrière-plans colorés des cellules",
        "es": "Aplicar opacidad a los fondos de celda con color",
        "hi": "रंगीन सेल पृष्ठभूमि पर भी अपारदर्शिता लागू करें",
        "ru": "Применять непрозрачность к цветному фону ячеек",
    },
    "Also applies the selected opacity to background colors set by terminal programs, including inverse video.": {
        "zh-Hans": "还会将所选不透明度应用于终端程序设置的背景颜色，包括反显背景。",
        "zh-Hant": "也會將所選不透明度套用至終端機程式設定的背景顏色，包括反相顯示背景。",
        "ja": "ターミナルプログラムが設定した背景色（反転表示を含む）にも、選択した不透明度を適用します。",
        "ko": "터미널 프로그램이 설정한 배경색(반전 표시 포함)에도 선택한 불투명도를 적용합니다.",
        "fr": "Applique aussi l’opacité choisie aux couleurs d’arrière-plan définies par les programmes du terminal, y compris en vidéo inversée.",
        "es": "También aplica la opacidad elegida a los colores de fondo definidos por los programas del terminal, incluido el vídeo inverso.",
        "hi": "चुनी गई अपारदर्शिता को टर्मिनल प्रोग्राम द्वारा सेट किए गए पृष्ठभूमि रंगों पर भी लागू करता है, जिसमें उलटा वीडियो भी शामिल है।",
        "ru": "Также применяет выбранную непрозрачность к цветам фона, заданным терминальными программами, включая инверсное отображение.",
    },
    "Terminal": {
        "zh-Hans": "终端",
        "zh-Hant": "終端機",
        "ja": "ターミナル",
        "ko": "터미널",
        "fr": "Terminal",
        "es": "Terminal",
        "hi": "टर्मिनल",
        "ru": "Терминал",
    },
    "Rendering": {
        "zh-Hans": "渲染",
        "zh-Hant": "渲染",
        "ja": "レンダリング",
        "ko": "렌더링",
        "fr": "Rendu",
        "es": "Renderizado",
        "hi": "रेंडरिंग",
        "ru": "Рендеринг",
    },
    "Notifications": {
        "zh-Hans": "通知",
        "zh-Hant": "通知",
        "ja": "通知",
        "ko": "알림",
        "fr": "Notifications",
        "es": "Notificaciones",
        "hi": "सूचनाएँ",
        "ru": "Уведомления",
    },
    "Theme:": {
        "zh-Hans": "主题：",
        "zh-Hant": "主題：",
        "ja": "テーマ：",
        "ko": "테마:",
        "fr": "Thème :",
        "es": "Tema:",
        "hi": "थीम:",
        "ru": "Тема:",
    },
    "Font:": {
        "zh-Hans": "字体：",
        "zh-Hant": "字體：",
        "ja": "フォント：",
        "ko": "글꼴:",
        "fr": "Police :",
        "es": "Fuente:",
        "hi": "फ़ॉन्ट:",
        "ru": "Шрифт:",
    },
    "CJK font:": {
        "zh-Hans": "CJK 字体：",
        "zh-Hant": "CJK 字體：",
        "ja": "CJK フォント：",
        "ko": "CJK 글꼴:",
        "fr": "Police CJK :",
        "es": "Fuente CJK:",
        "hi": "CJK फ़ॉन्ट:",
        "ru": "Шрифт CJK:",
    },
    "Cursor:": {
        "zh-Hans": "光标：",
        "zh-Hant": "游標：",
        "ja": "カーソル：",
        "ko": "커서:",
        "fr": "Curseur :",
        "es": "Cursor:",
        "hi": "कर्सर:",
        "ru": "Курсор:",
    },
    "Scroll:": {
        "zh-Hans": "滚动：",
        "zh-Hant": "捲動：",
        "ja": "スクロール：",
        "ko": "스크롤:",
        "fr": "Défilement :",
        "es": "Desplazamiento:",
        "hi": "स्क्रॉल:",
        "ru": "Прокрутка:",
    },
    "Unicode width:": {
        "zh-Hans": "Unicode 宽度：",
        "zh-Hant": "Unicode 寬度：",
        "ja": "Unicode 幅：",
        "ko": "Unicode 너비:",
        "fr": "Largeur Unicode :",
        "es": "Ancho Unicode:",
        "hi": "Unicode चौड़ाई:",
        "ru": "Ширина Unicode:",
    },
    "Sessions:": {
        "zh-Hans": "会话：",
        "zh-Hant": "工作階段：",
        "ja": "セッション：",
        "ko": "세션:",
        "fr": "Sessions :",
        "es": "Sesiones:",
        "hi": "सत्र:",
        "ru": "Сеансы:",
    },
    "Identity:": {
        "zh-Hans": "标识：",
        "zh-Hant": "識別：",
        "ja": "識別：",
        "ko": "식별:",
        "fr": "Identité :",
        "es": "Identidad:",
        "hi": "पहचान:",
        "ru": "Идентичность:",
    },
    "Renderer:": {
        "zh-Hans": "渲染器：",
        "zh-Hant": "渲染器：",
        "ja": "レンダラー：",
        "ko": "렌더러:",
        "fr": "Moteur de rendu :",
        "es": "Motor de renderizado:",
        "hi": "रेंडरर:",
        "ru": "Рендерер:",
    },
    "Emoji rendering:": {
        "zh-Hans": "表情符号渲染：",
        "zh-Hant": "表情符號渲染：",
        "ja": "絵文字レンダリング：",
        "ko": "이모지 렌더링:",
        "fr": "Rendu des emoji :",
        "es": "Renderizado de emoji:",
        "hi": "इमोजी रेंडरिंग:",
        "ru": "Рендеринг эмодзи:",
    },
    "Vector text AA:": {
        "zh-Hans": "矢量文字抗锯齿：",
        "zh-Hant": "向量文字反鋸齒：",
        "ja": "ベクターテキスト AA：",
        "ko": "벡터 텍스트 AA:",
        "fr": "AA texte vectoriel :",
        "es": "AA de texto vectorial:",
        "hi": "वेक्टर टेक्स्ट AA:",
        "ru": "Сглаживание векторного текста:",
    },
    "Overlap:": {
        "zh-Hans": "重叠：",
        "zh-Hant": "重疊：",
        "ja": "オーバーラップ：",
        "ko": "겹침:",
        "fr": "Chevauchement :",
        "es": "Superposición:",
        "hi": "ओवरलैप:",
        "ru": "Перекрытие:",
    },
    "Text weight:": {
        "zh-Hans": "字重：",
        "zh-Hant": "字重：",
        "ja": "文字の太さ：",
        "ko": "글자 굵기:",
        "fr": "Épaisseur du texte :",
        "es": "Peso del texto:",
        "hi": "टेक्स्ट वज़न:",
        "ru": "Толщина текста:",
    },
    "Smooth scroll:": {
        "zh-Hans": "平滑滚动：",
        "zh-Hant": "平滑捲動：",
        "ja": "スムーズスクロール：",
        "ko": "부드러운 스크롤:",
        "fr": "Défilement fluide :",
        "es": "Desplazamiento suave:",
        "hi": "स्मूथ स्क्रॉल:",
        "ru": "Плавная прокрутка:",
    },
    "Thin": {
        "zh-Hans": "细",
        "zh-Hant": "細",
        "ja": "細い",
        "ko": "얇게",
        "fr": "Fin",
        "es": "Fino",
        "hi": "पतला",
        "ru": "Тонкий",
    },
    "Heavy": {
        "zh-Hans": "粗",
        "zh-Hant": "粗",
        "ja": "太い",
        "ko": "굵게",
        "fr": "Épais",
        "es": "Grueso",
        "hi": "मोटा",
        "ru": "Жирный",
    },
    # Settings option values
    "Software": {
        "zh-Hans": "软件",
        "zh-Hant": "軟體",
        "ja": "ソフトウェア",
        "ko": "소프트웨어",
        "fr": "Logiciel",
        "es": "Software",
        "hi": "सॉफ़्टवेयर",
        "ru": "Программный",
    },
    "Classic (Metal)": {
        "zh-Hans": "经典 (Metal)",
        "zh-Hant": "經典 (Metal)",
        "ja": "クラシック (Metal)",
        "ko": "클래식 (Metal)",
        "fr": "Classique (Metal)",
        "es": "Clásico (Metal)",
        "hi": "क्लासिक (Metal)",
        "ru": "Классический (Metal)",
    },
    "GPU-driven (Metal)": {
        "zh-Hans": "GPU 驱动 (Metal)",
        "zh-Hant": "GPU 驅動 (Metal)",
        "ja": "GPU 駆動 (Metal)",
        "ko": "GPU 기반 (Metal)",
        "fr": "Piloté par GPU (Metal)",
        "es": "Por GPU (Metal)",
        "hi": "GPU-संचालित (Metal)",
        "ru": "GPU (Metal)",
    },
    "GPU-driven (requires macOS 26)": {
        "zh-Hans": "GPU 驱动（需要 macOS 26）",
        "zh-Hant": "GPU 驅動（需要 macOS 26）",
        "ja": "GPU 駆動（macOS 26 が必要）",
        "ko": "GPU 기반(macOS 26 필요)",
        "fr": "Piloté par GPU (macOS 26 requis)",
        "es": "Por GPU (requiere macOS 26)",
        "hi": "GPU-संचालित (macOS 26 आवश्यक)",
        "ru": "GPU (требуется macOS 26)",
    },
    "Vector Glyph": {
        "zh-Hans": "矢量字形",
        "zh-Hant": "向量字形",
        "ja": "ベクターグリフ",
        "ko": "벡터 글리프",
        "fr": "Vector Glyph",
        "es": "Vector Glyph",
        "hi": "वेक्टर ग्लिफ़",
        "ru": "Vector Glyph",
    },
    "Slug Glyph": {
        "zh-Hans": "Slug 字形",
        "zh-Hant": "Slug 字形",
        "ja": "Slug グリフ",
        "ko": "Slug 글리프",
        "fr": "Slug Glyph",
        "es": "Slug Glyph",
        "hi": "Slug ग्लिफ़",
        "ru": "Slug Glyph",
    },
    "Local": {
        "zh-Hans": "本地",
        "zh-Hant": "本機",
        "ja": "ローカル",
        "ko": "로컬",
        "fr": "Local",
        "es": "Local",
        "hi": "स्थानीय",
        "ru": "Локальный",
    },
    "Background": {
        "zh-Hans": "后台",
        "zh-Hant": "背景",
        "ja": "バックグラウンド",
        "ko": "백그라운드",
        "fr": "Arrière-plan",
        "es": "Segundo plano",
        "hi": "पृष्ठभूमि",
        "ru": "Фоновый",
    },
    "Detached": {
        "zh-Hans": "独立",
        "zh-Hant": "獨立",
        "ja": "デタッチ",
        "ko": "분리",
        "fr": "Détaché",
        "es": "Independiente",
        "hi": "अलग",
        "ru": "Отдельный",
    },
    "Block": {
        "zh-Hans": "方块",
        "zh-Hant": "方塊",
        "ja": "ブロック",
        "ko": "블록",
        "fr": "Bloc",
        "es": "Bloque",
        "hi": "ब्लॉक",
        "ru": "Блок",
    },
    "Bar": {
        "zh-Hans": "竖线",
        "zh-Hant": "豎線",
        "ja": "バー",
        "ko": "막대",
        "fr": "Barre",
        "es": "Barra",
        "hi": "बार",
        "ru": "Полоса",
    },
    "Underline": {
        "zh-Hans": "下划线",
        "zh-Hant": "底線",
        "ja": "下線",
        "ko": "밑줄",
        "fr": "Souligné",
        "es": "Subrayado",
        "hi": "रेखांकन",
        "ru": "Подчёркивание",
    },
    "Pixel-smooth": {
        "zh-Hans": "像素平滑",
        "zh-Hant": "像素平滑",
        "ja": "ピクセルスムーズ",
        "ko": "픽셀 부드럽게",
        "fr": "Lissage par pixel",
        "es": "Suave por píxel",
        "hi": "पिक्सेल-स्मूथ",
        "ru": "Пиксельное сглаживание",
    },
    "Line-quantized": {
        "zh-Hans": "按行量化",
        "zh-Hant": "按行量化",
        "ja": "行単位",
        "ko": "줄 단위",
        "fr": "Quantifié par ligne",
        "es": "Cuantizado por línea",
        "hi": "पंक्ति-क्वांटाइज़्ड",
        "ru": "Построчная прокрутка",
    },
    "Auto (recommended)": {
        "zh-Hans": "自动（推荐）",
        "zh-Hant": "自動（建議）",
        "ja": "自動（推奨）",
        "ko": "자동(권장)",
        "fr": "Auto (recommandé)",
        "es": "Automático (recomendado)",
        "hi": "स्वचालित (अनुशंसित)",
        "ru": "Авто (рекомендуется)",
    },
    "Prefer grapheme width": {
        "zh-Hans": "优先字素宽度",
        "zh-Hant": "優先字素寬度",
        "ja": "書記素幅を優先",
        "ko": "자소 너비 우선",
        "fr": "Préférer la largeur graphémique",
        "es": "Preferir ancho de grafema",
        "hi": "ग्राफ़ेम चौड़ाई प्राथमिकता",
        "ru": "Предпочитать ширину графемы",
    },
    "Monochrome": {
        "zh-Hans": "单色",
        "zh-Hant": "單色",
        "ja": "モノクロ",
        "ko": "단색",
        "fr": "Monochrome",
        "es": "Monocromo",
        "hi": "मोनोक्रोम",
        "ru": "Монохром",
    },
    "Color": {
        "zh-Hans": "彩色",
        "zh-Hant": "彩色",
        "ja": "カラー",
        "ko": "컬러",
        "fr": "Couleur",
        "es": "Color",
        "hi": "रंग",
        "ru": "Цветной",
    },
    "Grayscale": {
        "zh-Hans": "灰度",
        "zh-Hant": "灰階",
        "ja": "グレースケール",
        "ko": "그레이스케일",
        "fr": "Niveaux de gris",
        "es": "Escala de grises",
        "hi": "ग्रेस्केल",
        "ru": "Оттенки серого",
    },
    "Calibrated": {
        "zh-Hans": "校准",
        "zh-Hant": "校準",
        "ja": "キャリブレーション",
        "ko": "보정",
        "fr": "Calibré",
        "es": "Calibrado",
        "hi": "कैलिब्रेटेड",
        "ru": "Калиброванный",
    },
    "Custom overlap": {
        "zh-Hans": "自定义重叠",
        "zh-Hant": "自訂重疊",
        "ja": "カスタムオーバーラップ",
        "ko": "사용자 겹침",
        "fr": "Chevauchement personnalisé",
        "es": "Superposición personalizada",
        "hi": "कस्टम ओवरलैप",
        "ru": "Пользовательское перекрытие",
    },
    "RGB subpixel": {
        "zh-Hans": "RGB 子像素",
        "zh-Hant": "RGB 子像素",
        "ja": "RGB サブピクセル",
        "ko": "RGB 서브픽셀",
        "fr": "Sous-pixel RGB",
        "es": "Subpíxel RGB",
        "hi": "RGB सबपिक्सेल",
        "ru": "RGB субпиксель",
    },
    "BGR subpixel": {
        "zh-Hans": "BGR 子像素",
        "zh-Hant": "BGR 子像素",
        "ja": "BGR サブピクセル",
        "ko": "BGR 서브픽셀",
        "fr": "Sous-pixel BGR",
        "es": "Subpíxel BGR",
        "hi": "BGR सबपिक्सेल",
        "ru": "BGR субпиксель",
    },
    "Fluid": {
        "zh-Hans": "流畅",
        "zh-Hant": "流暢",
        "ja": "フルイド",
        "ko": "유동",
        "fr": "Fluide",
        "es": "Fluido",
        "hi": "फ़्लुइड",
        "ru": "Плавный",
    },
    "Crisp": {
        "zh-Hans": "清晰",
        "zh-Hant": "清晰",
        "ja": "くっきり",
        "ko": "선명",
        "fr": "Net",
        "es": "Nítido",
        "hi": "क्रिस्प",
        "ru": "Чёткий",
    },
    # Common buttons / alerts
    "OK": {
        "zh-Hans": "好",
        "zh-Hant": "好",
        "ja": "OK",
        "ko": "확인",
        "fr": "OK",
        "es": "Aceptar",
        "hi": "ठीक",
        "ru": "OK",
    },
    "Cancel": {
        "zh-Hans": "取消",
        "zh-Hant": "取消",
        "ja": "キャンセル",
        "ko": "취소",
        "fr": "Annuler",
        "es": "Cancelar",
        "hi": "रद्द करें",
        "ru": "Отменить",
    },
    "Quit": {
        "zh-Hans": "退出",
        "zh-Hant": "結束",
        "ja": "終了",
        "ko": "종료",
        "fr": "Quitter",
        "es": "Salir",
        "hi": "बंद करें",
        "ru": "Выйти",
    },
    "Restart Now": {
        "zh-Hans": "立即重启",
        "zh-Hant": "立即重新啟動",
        "ja": "今すぐ再起動",
        "ko": "지금 다시 시작",
        "fr": "Redémarrer maintenant",
        "es": "Reiniciar ahora",
        "hi": "अभी पुनः प्रारंभ करें",
        "ru": "Перезапустить сейчас",
    },
    "Later": {
        "zh-Hans": "稍后",
        "zh-Hant": "稍後",
        "ja": "あとで",
        "ko": "나중에",
        "fr": "Plus tard",
        "es": "Más tarde",
        "hi": "बाद में",
        "ru": "Позже",
    },
    "Done": {
        "zh-Hans": "完成",
        "zh-Hant": "完成",
        "ja": "完了",
        "ko": "완료",
        "fr": "Terminé",
        "es": "Listo",
        "hi": "पूर्ण",
        "ru": "Готово",
    },
    "Open Settings": {
        "zh-Hans": "打开设置",
        "zh-Hant": "打開設定",
        "ja": "設定を開く",
        "ko": "설정 열기",
        "fr": "Ouvrir les réglages",
        "es": "Abrir ajustes",
        "hi": "सेटिंग्स खोलें",
        "ru": "Открыть настройки",
    },
    "Reveal in Finder": {
        "zh-Hans": "在 Finder 中显示",
        "zh-Hant": "在 Finder 中顯示",
        "ja": "Finder で表示",
        "ko": "Finder에서 보기",
        "fr": "Afficher dans le Finder",
        "es": "Mostrar en Finder",
        "hi": "Finder में दिखाएँ",
        "ru": "Показать в Finder",
    },
    "Notifications are off for Laban": {
        "zh-Hans": "Laban 的通知已关闭",
        "zh-Hant": "Laban 的通知已關閉",
        "ja": "Laban の通知がオフです",
        "ko": "Laban 알림이 꺼져 있습니다",
        "fr": "Les notifications sont désactivées pour Laban",
        "es": "Las notificaciones están desactivadas para Laban",
        "hi": "Laban के लिए सूचनाएँ बंद हैं",
        "ru": "Уведомления для Laban отключены",
    },
    "Enable Laban in System Settings > Notifications, and choose Banners or Alerts, to receive tab attention notifications.": {
        "zh-Hans": "在系统设置 > 通知中启用 Laban，并选择横幅或提醒，以接收标签页提醒通知。",
        "zh-Hant": "在系統設定 > 通知中啟用 Laban，並選擇橫幅或提醒，以接收標籤頁提醒通知。",
        "ja": "システム設定 > 通知で Laban を有効にし、バナーまたはアラートを選択してタブ注意通知を受け取ります。",
        "ko": "시스템 설정 > 알림에서 Laban을 켜고 배너 또는 알림을 선택해 탭 주의 알림을 받으세요.",
        "fr": "Activez Laban dans Réglages système > Notifications et choisissez Bannières ou Alertes pour recevoir les notifications d’onglet.",
        "es": "Activa Laban en Ajustes del sistema > Notificaciones y elige Banners o Alertas para recibir notificaciones de pestaña.",
        "hi": "सिस्टम सेटिंग्स > सूचनाएँ में Laban सक्षम करें और टैब ध्यान सूचनाएँ पाने के लिए बैनर या अलर्ट चुनें।",
        "ru": "Включите Laban в Системных настройках > Уведомления и выберите Баннеры или Оповещения для уведомлений о вкладках.",
    },
    "Laban failed to start": {
        "zh-Hans": "Laban 启动失败",
        "zh-Hant": "Laban 啟動失敗",
        "ja": "Laban の起動に失敗しました",
        "ko": "Laban을 시작하지 못했습니다",
        "fr": "Échec du démarrage de Laban",
        "es": "Laban no pudo iniciarse",
        "hi": "Laban शुरू नहीं हो सका",
        "ru": "Не удалось запустить Laban",
    },
    "Background terminal sessions failed to start": {
        "zh-Hans": "后台终端会话启动失败",
        "zh-Hant": "背景終端機工作階段啟動失敗",
        "ja": "バックグラウンドターミナルセッションの起動に失敗しました",
        "ko": "백그라운드 터미널 세션을 시작하지 못했습니다",
        "fr": "Échec du démarrage des sessions de terminal en arrière-plan",
        "es": "No se pudieron iniciar las sesiones de terminal en segundo plano",
        "hi": "पृष्ठभूमि टर्मिनल सत्र शुरू नहीं हो सके",
        "ru": "Не удалось запустить фоновые сеансы терминала",
    },
    "Use Local Sessions": {
        "zh-Hans": "使用本地会话",
        "zh-Hant": "使用本機工作階段",
        "ja": "ローカルセッションを使用",
        "ko": "로컬 세션 사용",
        "fr": "Utiliser les sessions locales",
        "es": "Usar sesiones locales",
        "hi": "स्थानीय सत्र उपयोग करें",
        "ru": "Использовать локальные сеансы",
    },
    "Restart Laban to use %@ sessions?": {
        "zh-Hans": "重新启动 Laban 以使用%@会话？",
        "zh-Hant": "重新啟動 Laban 以使用%@工作階段？",
        "ja": "%@セッションを使うには Laban を再起動しますか？",
        "ko": "%@ 세션을 사용하려면 Laban을 다시 시작할까요?",
        "fr": "Redémarrer Laban pour utiliser les sessions %@ ?",
        "es": "¿Reiniciar Laban para usar sesiones %@?",
        "hi": "%@ सत्र उपयोग करने के लिए Laban पुनः प्रारंभ करें?",
        "ru": "Перезапустить Laban для сеансов %@?",
    },
    "Existing tabs stay on the current session backend until Laban restarts.": {
        "zh-Hans": "现有标签页将保持当前会话后端，直到 Laban 重新启动。",
        "zh-Hant": "現有標籤頁將保持目前工作階段後端，直到 Laban 重新啟動。",
        "ja": "Laban を再起動するまで、既存のタブは現在のセッションバックエンドのままです。",
        "ko": "Laban을 다시 시작할 때까지 기존 탭은 현재 세션 백엔드를 유지합니다.",
        "fr": "Les onglets existants restent sur le backend de session actuel jusqu’au redémarrage de Laban.",
        "es": "Las pestañas existentes permanecen en el backend de sesión actual hasta reiniciar Laban.",
        "hi": "Laban पुनः प्रारंभ होने तक मौजूदा टैब वर्तमान सत्र बैकएंड पर रहेंगे।",
        "ru": "Существующие вкладки остаются на текущем бэкенде сеансов до перезапуска Laban.",
    },
    "Adopt": {
        "zh-Hans": "采用",
        "zh-Hant": "採用",
        "ja": "取り込む",
        "ko": "가져오기",
        "fr": "Adopter",
        "es": "Adoptar",
        "hi": "अपनाएँ",
        "ru": "Принять",
    },
    "Ignore": {
        "zh-Hans": "忽略",
        "zh-Hant": "忽略",
        "ja": "無視",
        "ko": "무시",
        "fr": "Ignorer",
        "es": "Ignorar",
        "hi": "अनदेखा करें",
        "ru": "Игнорировать",
    },
    "A background terminal session has no tab": {
        "zh-Hans": "一个后台终端会话没有标签页",
        "zh-Hant": "一個背景終端機工作階段沒有標籤頁",
        "ja": "バックグラウンドのターミナルセッションにタブがありません",
        "ko": "백그라운드 터미널 세션에 탭이 없습니다",
        "fr": "Une session de terminal en arrière-plan n’a pas d’onglet",
        "es": "Una sesión de terminal en segundo plano no tiene pestaña",
        "hi": "एक पृष्ठभूमि टर्मिनल सत्र में कोई टैब नहीं है",
        "ru": "У фонового сеанса терминала нет вкладки",
    },
    "%lld background terminal sessions have no tabs": {
        "zh-Hans": "%lld 个后台终端会话没有标签页",
        "zh-Hant": "%lld 個背景終端機工作階段沒有標籤頁",
        "ja": "%lld 個のバックグラウンドターミナルセッションにタブがありません",
        "ko": "%lld개의 백그라운드 터미널 세션에 탭이 없습니다",
        "fr": "%lld sessions de terminal en arrière-plan n’ont pas d’onglet",
        "es": "%lld sesiones de terminal en segundo plano no tienen pestañas",
        "hi": "%lld पृष्ठभूमि टर्मिनल सत्रों में कोई टैब नहीं है",
        "ru": "У %lld фоновых сеансов терминала нет вкладок",
    },
    "Laban found live shell session(s) from a previous run that aren't open in this window. Adopt them to reopen them as tabs, or ignore to leave them running in the background.": {
        "zh-Hans": "Laban 发现上次运行中仍在运行的 shell 会话未在此窗口中打开。采用它们可重新打开为标签页，忽略则继续在后台运行。",
        "zh-Hant": "Laban 發現上次執行中仍在運行的 shell 工作階段未在此視窗中開啟。採用它們可重新開啟為標籤頁，忽略則繼續在背景運行。",
        "ja": "前回の実行から存続しているシェルセッションがこのウィンドウで開かれていません。取り込むとタブとして再開し、無視するとバックグラウンドで実行を続けます。",
        "ko": "이전 실행에서 살아 있는 셸 세션이 이 창에 열려 있지 않습니다. 가져오면 탭으로 다시 열고, 무시하면 백그라운드에서 계속 실행됩니다.",
        "fr": "Laban a trouvé des sessions shell actives d’une exécution précédente qui ne sont pas ouvertes dans cette fenêtre. Adoptez-les pour les rouvrir en onglets, ou ignorez pour les laisser en arrière-plan.",
        "es": "Laban encontró sesiones de shell activas de una ejecución anterior que no están abiertas en esta ventana. Adóptalas para reabrirlas como pestañas o ignóralas para dejarlas en segundo plano.",
        "hi": "Laban ने पिछले रन से जीवित शेल सत्र पाए जो इस विंडो में खुले नहीं हैं। टैब के रूप में फिर खोलने के लिए अपनाएँ, या पृष्ठभूमि में चलने देने के लिए अनदेखा करें।",
        "ru": "Laban обнаружил активные сеансы shell с прошлого запуска, не открытые в этом окне. Примите их, чтобы открыть как вкладки, или игнорируйте, чтобы оставить в фоне.",
    },
    "Recording PTY capture": {
        "zh-Hans": "正在录制 PTY 捕获",
        "zh-Hant": "正在錄製 PTY 擷取",
        "ja": "PTY キャプチャを記録中",
        "ko": "PTY 캡처 녹화 중",
        "fr": "Enregistrement de capture PTY",
        "es": "Grabando captura PTY",
        "hi": "PTY कैप्चर रिकॉर्ड हो रहा है",
        "ru": "Запись захвата PTY",
    },
    "Capturing CPU profile": {
        "zh-Hans": "正在捕获 CPU 配置文件",
        "zh-Hant": "正在擷取 CPU 設定檔",
        "ja": "CPU プロファイルを取得中",
        "ko": "CPU 프로파일 캡처 중",
        "fr": "Capture du profil CPU",
        "es": "Capturando perfil de CPU",
        "hi": "CPU प्रोफ़ाइल कैप्चर हो रही है",
        "ru": "Снятие профиля CPU",
    },
    "Paste too large": {
        "zh-Hans": "粘贴内容过大",
        "zh-Hant": "貼上內容過大",
        "ja": "ペーストが大きすぎます",
        "ko": "붙여넣기가 너무 큽니다",
        "fr": "Collage trop volumineux",
        "es": "Pegado demasiado grande",
        "hi": "पेस्ट बहुत बड़ा है",
        "ru": "Слишком большая вставка",
    },
    "Large paste": {
        "zh-Hans": "大量粘贴",
        "zh-Hant": "大量貼上",
        "ja": "大きなペースト",
        "ko": "큰 붙여넣기",
        "fr": "Collage volumineux",
        "es": "Pegado grande",
        "hi": "बड़ा पेस्ट",
        "ru": "Большая вставка",
    },
    "About to paste %lld bytes. Continue?": {
        "zh-Hans": "即将粘贴 %lld 字节。继续？",
        "zh-Hant": "即將貼上 %lld 位元組。繼續？",
        "ja": "%lld バイトをペーストします。続行しますか？",
        "ko": "%lld바이트를 붙여넣습니다. 계속할까요?",
        "fr": "Collage de %lld octets imminent. Continuer ?",
        "es": "A punto de pegar %lld bytes. ¿Continuar?",
        "hi": "%lld बाइट पेस्ट करने वाले हैं। जारी रखें?",
        "ru": "Будет вставлено %lld байт. Продолжить?",
    },
    "Paste contains control characters or newlines": {
        "zh-Hans": "粘贴内容包含控制字符或换行符",
        "zh-Hant": "貼上內容包含控制字元或換行",
        "ja": "ペーストに制御文字または改行が含まれています",
        "ko": "붙여넣기에 제어 문자 또는 줄바꿈이 포함되어 있습니다",
        "fr": "Le collage contient des caractères de contrôle ou des sauts de ligne",
        "es": "El pegado contiene caracteres de control o saltos de línea",
        "hi": "पेस्ट में नियंत्रण वर्ण या नई पंक्तियाँ हैं",
        "ru": "Вставка содержит управляющие символы или переводы строк",
    },
    "The active program isn't using bracketed paste. Pasting may run each line as a command. Continue?": {
        "zh-Hans": "当前程序未使用括号粘贴模式。粘贴可能会将每行作为命令执行。继续？",
        "zh-Hant": "目前程式未使用括號貼上模式。貼上可能會將每行作為指令執行。繼續？",
        "ja": "アクティブなプログラムは bracketed paste を使用していません。ペーストすると各行がコマンドとして実行される可能性があります。続行しますか？",
        "ko": "활성 프로그램이 bracketed paste를 사용하지 않습니다. 붙여넣으면 각 줄이 명령으로 실행될 수 있습니다. 계속할까요?",
        "fr": "Le programme actif n’utilise pas le collage entre crochets. Coller peut exécuter chaque ligne comme une commande. Continuer ?",
        "es": "El programa activo no usa pegado entre corchetes. Pegar puede ejecutar cada línea como un comando. ¿Continuar?",
        "hi": "सक्रिय प्रोग्राम bracketed paste का उपयोग नहीं कर रहा। पेस्ट करने पर प्रत्येक पंक्ति कमांड के रूप में चल सकती है। जारी रखें?",
        "ru": "Активная программа не использует bracketed paste. Вставка может выполнить каждую строку как команду. Продолжить?",
    },
    "No active tab": {
        "zh-Hans": "没有活动标签页",
        "zh-Hant": "沒有使用中標籤頁",
        "ja": "アクティブなタブがありません",
        "ko": "활성 탭 없음",
        "fr": "Aucun onglet actif",
        "es": "No hay pestaña activa",
        "hi": "कोई सक्रिय टैब नहीं",
        "ru": "Нет активной вкладки",
    },
    "Open a tab and try again.": {
        "zh-Hans": "打开一个标签页后重试。",
        "zh-Hant": "開啟一個標籤頁後再試。",
        "ja": "タブを開いてから再試行してください。",
        "ko": "탭을 연 후 다시 시도하세요.",
        "fr": "Ouvrez un onglet et réessayez.",
        "es": "Abre una pestaña e inténtalo de nuevo.",
        "hi": "एक टैब खोलें और पुनः प्रयास करें।",
        "ru": "Откройте вкладку и повторите попытку.",
    },
    "(not installed)": {
        "zh-Hans": "（未安装）",
        "zh-Hant": "（未安裝）",
        "ja": "（未インストール）",
        "ko": "(설치되지 않음)",
        "fr": "(non installé)",
        "es": "(no instalado)",
        "hi": "(स्थापित नहीं)",
        "ru": "(не установлено)",
    },
    "Font set to %@, %@": {
        "zh-Hans": "字体已设置为 %@, %@",
        "zh-Hant": "字型已設定為 %@, %@",
        "ja": "フォントが %@, %@ に設定されました",
        "ko": "글꼴이 %@, %@(으)로 설정되었습니다",
        "fr": "Police définie sur %@, %@",
        "es": "Fuente configurada en %@, %@",
        "hi": "फ़ॉन्ट %@, %@ पर सेट किया गया",
        "ru": "Установлен шрифт %@, %@",
    },
    "Restart Laban to apply.": {
        "zh-Hans": "重启 Laban 以应用。",
        "zh-Hant": "重新啟動 Laban 以套用。",
        "ja": "適用するには Laban を再起動してください。",
        "ko": "적용하려면 Laban을 다시 시작하십시오.",
        "fr": "Redémarrez Laban pour appliquer.",
        "es": "Reinicia Laban para aplicar.",
        "hi": "लागू करने के लिए Laban को पुनः प्रारंभ करें।",
        "ru": "Перезапустите Laban для применения.",
    },
    "Font cannot render CJK text": {
        "zh-Hans": "字体无法渲染 CJK 文本",
        "zh-Hant": "字型無法轉譯 CJK 文字",
        "ja": "フォントが CJK テキストをレンダリングできません",
        "ko": "글꼴이 CJK 텍스트를 렌더링할 수 없습니다",
        "fr": "La police ne peut pas afficher le texte CJK",
        "es": "La fuente no puede renderizar texto CJK",
        "hi": "फ़ॉन्ट CJK टेक्स्ट को रेंडर नहीं कर सकता",
        "ru": "Шрифт не поддерживает CJK",
    },
    "%@ does not provide a usable Han glyph at the terminal size. Pick a font that includes simplified Chinese, traditional Chinese, Japanese, or Korean characters.": {
        "zh-Hans": "%@ 在终端大小下未提供可用的汉字字形。请选择包含简体中文、繁体中文、日语或韩文字符的字体。",
        "zh-Hant": "%@ 在終端機大小下未提供可用的漢字字形。請選擇包含簡體中文、繁體中文、日語或韓文字元的字型。",
        "ja": "%@ はターミナルサイズで利用可能な漢字グリフを提供していません。簡体字中国語、繁体字中国語、日本語、または韓国語の文字を含むフォントを選択してください。",
        "ko": "%@은(는) 터미널 크기에서 사용할 수 있는 한자 글리프를 제공하지 않습니다. 간체 중국어, 번체 중국어, 일본어 또는 한국어 문자가 포함된 글꼴을 선택하십시오.",
        "fr": "%@ ne fournit pas de glyphe Han utilisable à la taille du terminal. Choisissez une police qui inclut des caractères chinois simplifiés, chinois traditionnels, japonais ou coréens.",
        "es": "%@ no proporciona un glifo Han utilizable al tamaño del terminal. Elige una fuente que incluya caracteres en chino simplificado, chino tradicional, japonés o coreano.",
        "hi": "%@ टर्मिनल आकार पर एक उपयोगी हान ग्लिफ प्रदान नहीं करता है। ऐसा फ़ॉन्ट चुनें जिसमें सरलीकृत चीनी, पारंपरिक चीनी, जापानी या कोरियाई वर्ण शामिल हों।",
        "ru": "%@ не предоставляет пригодного для использования иероглифа Han для размера терминала. Выберите шрифт, содержащий символы упрощенного китайского, традиционного китайского, японского или корейского языков.",
    },
    "Update check failed": {
        "zh-Hans": "更新检查失败",
        "zh-Hant": "更新檢查失敗",
        "ja": "更新の確認に失敗しました",
        "ko": "업데이트 확인 실패",
        "fr": "Échec de la vérification des mises à jour",
        "es": "Error al buscar actualizaciones",
        "hi": "अपडेट जाँच विफल रही",
        "ru": "Ошибка проверки обновлений",
    },
    "Laban %@ is available": {
        "zh-Hans": "Laban %@ 可用",
        "zh-Hant": "Laban %@ 可用",
        "ja": "Laban %@ が利用可能です",
        "ko": "Laban %@이(가) 사용 가능합니다",
        "fr": "Laban %@ est disponible",
        "es": "Laban %@ está disponible",
        "hi": "Laban %@ उपलब्ध है",
        "ru": "Доступна версия Laban %@",
    },
    "You are running %@.": {
        "zh-Hans": "您正在运行 %@。",
        "zh-Hant": "您正在執行 %@。",
        "ja": "現在実行中のバージョンは %@ です。",
        "ko": "현재 %@ 버전을 실행 중입니다.",
        "fr": "Vous utilisez la version %@.",
        "es": "Estás ejecutando la versión %@.",
        "hi": "आप %@ चला रहे हैं।",
        "ru": "Вы используете версию %@.",
    },
    "Open Download": {
        "zh-Hans": "打开下载",
        "zh-Hant": "開啟下載",
        "ja": "ダウンロードを開く",
        "ko": "다운로드 열기",
        "fr": "Ouvrir le téléchargement",
        "es": "Abrir descarga",
        "hi": "다운लोड खोलें",
        "ru": "Открыть загрузку",
    },
    "Not Now": {
        "zh-Hans": "以后再说",
        "zh-Hant": "以後再說",
        "ja": "今はしない",
        "ko": "나중에",
        "fr": "Pas maintenant",
        "es": "Ahora no",
        "hi": "अभी नहीं",
        "ru": "Не сейчас",
    },
    "Exported last %lld s to a cast file": {
        "zh-Hans": "已导出最近 %lld 秒到 Cast 文件",
        "zh-Hant": "已匯出最近 %lld 秒到 Cast 檔案",
        "ja": "直近 %lld 秒を Cast ファイルに書き出しました",
        "ko": "최근 %lld초가 Cast 파일로 내보내졌습니다",
        "fr": "Les dernières %lld s ont été exportées dans un fichier Cast",
        "es": "Últimos %lld s exportados a un archivo Cast",
        "hi": "पिछले %lld सेकंड Cast फ़ाइल में निर्यात किए गए",
        "ru": "Последние %lld с экспортированы в файл Cast",
    },
    "Heads up: terminal output can contain secrets (tokens, keys, .env contents). Review the file before sharing it publicly.": {
        "zh-Hans": "提示：终端输出可能包含敏感信息（令牌、密钥、.env 内容）。在公开分享前请检查文件。",
        "zh-Hant": "提示：終端機輸出可能包含敏感資訊（金鑰、密鑰、.env 內容）。在公開分享前請檢查檔案。",
        "ja": "注意：ターミナルの出力には機密情報（トークン、キー、.envの内容など）が含まれる場合があります。公開共有する前にファイルを確認してください。",
        "ko": "주의: 터미널 출력에는 비밀 정보(토큰, 키, .env 내용)가 포함될 수 있습니다. 공개적으로 공유하기 전에 파일을 검토하십시오.",
        "fr": "Attention : la sortie du terminal peut contenir des secrets (jetons, clés, contenu .env). Vérifiez le fichier avant de le partager publiquement.",
        "es": "Atención: la salida del terminal puede contener secretos (tokens, claves, contenido de .env). Revisa el archivo antes de compartirlo públicamente.",
        "hi": "ध्यान दें: टर्मिनल आउटपुट में गोपनीय जानकारी (टोकन, चाबियां, .env सामग्री) हो सकती है। इसे सार्वजनिक रूप से साझा करने से पहले फ़ाइल की समीक्षा करें।",
        "ru": "Внимание: вывод терминала может содержать секретные данные (токены, ключи, содержимое .env). Проверьте файл перед публичным обменом.",
    },
    "Open in Browser": {
        "zh-Hans": "在浏览器中打开",
        "zh-Hant": "在瀏覽器中開啟",
        "ja": "ブラウザで開く",
        "ko": "브라우저에서 열기",
        "fr": "Ouvrir dans le navigateur",
        "es": "Abrir en el navegador",
        "hi": "ブラウザ में खोलें",
        "ru": "Открыть в браузере",
    },
    "Copy Path": {
        "zh-Hans": "复制路径",
        "zh-Hant": "複製路徑",
        "ja": "パスをコピー",
        "ko": "경로 복사",
        "fr": "Copier le chemin",
        "es": "Copiar ruta",
        "hi": "पथ कॉपी करें",
        "ru": "Копировать путь",
    },
    "Render Journal Is Disabled": {
        "zh-Hans": "渲染日志已禁用",
        "zh-Hant": "渲染日誌已停用",
        "ja": "レンダリングジャーナルは無効です",
        "ko": "렌더 저널이 비활성화되었습니다",
        "fr": "Le journal de rendu est désactivé",
        "es": "El diario de renderizado está desactivado",
        "hi": "रेंडर जर्नल अक्षम है",
        "ru": "Журнал рендеринга отключен",
    },
    "This launch is using a command-line or environment override. Remove that override for the saved menu choice to apply on restart.": {
        "zh-Hans": "本次启动使用了命令行或环境变量覆盖。请移除该覆盖，以便在重启时应用保存的菜单选择。",
        "zh-Hant": "本次啟動使用了命令列或環境變數覆蓋。請移除該覆蓋，以便在重啟時套用儲存的選單選擇。",
        "ja": "この起動では、コマンドラインまたは環境のオーバーライドが使用されています。再起動時に保存されたメニューの選択肢を適用するには、そのオーバーライドを削除してください。",
        "ko": "이 실행은 명령줄 또는 환경 재정의를 사용하고 있습니다. 재시작 시 저장된 메뉴 선택을 적용하려면 해당 재정의를 제거하십시오.",
        "fr": "Ce lancement utilise une substitution de ligne de commande ou d’environnement. Supprimez cette substitution pour que le choix de menu enregistré s’applique au redémarrage.",
        "es": "Este inicio utiliza una sustitución de línea de comandos o de entorno. Elimina esa sustitución para que la opción de menú guardada se aplique al reiniciar.",
        "hi": "यह लॉन्च कमांड-лайн या पर्यावरण ओवरराइड का उपयोग कर रहा है। पुनरारंभ करने पर सहेजे गए मेनू विकल्प को लागू करने के लिए उस ओवरराइड को हटा दें।",
        "ru": "Этот запуск использует переопределение командной строки или окружения. Удалите это переопределение, чтобы сохраненный выбор меню применился при перезапуске.",
    },
    "Refusing to paste %lld bytes (limit is %lld).": {
        "zh-Hans": "拒绝粘贴 %lld 字节（限制为 %lld）。",
        "zh-Hant": "拒絕貼上 %lld 位元組（限制為 %lld）。",
        "ja": "%lld バイトのペーストを拒否しました（制限は %lld です）。",
        "ko": "%lld 바이트 붙여넣기 거부(제한은 %lld임).",
        "fr": "Refus de coller %lld octets (la limite est de %lld).",
        "es": "Rechazo pegar %lld bytes (el límite es %lld).",
        "hi": "%lld बाइट्स पेस्ट करने से इनकार (सीमा %lld है)।",
        "ru": "Отказ во вставке %lld байт (лимит составляет %lld).",
    },
    "Saved under ~/Library/Logs/Laban/profiles/. Where should it open?": {
        "zh-Hans": "已保存至 ~/Library/Logs/Laban/profiles/。应该在哪里打开？",
        "zh-Hant": "已儲存至 ~/Library/Logs/Laban/profiles/。應該在哪裡開啟？",
        "ja": "~/Library/Logs/Laban/profiles/ に保存されました。どこで開きますか？",
        "ko": "~/Library/Logs/Laban/profiles/에 저장되었습니다. 어디에서 열어야 합니까?",
        "fr": "Enregistré sous ~/Library/Logs/Laban/profiles/. Où doit-il s’ouvrir ?",
        "es": "Guardado en ~/Library/Logs/Laban/profiles/. ¿Dónde debería abrirse?",
        "hi": "~/Library/Logs/Laban/profiles/ के तहत सहेजा गया। इसे कहाँ खोलना चाहिए?",
        "ru": "Сохранено в ~/Library/Logs/Laban/profiles/. Где это открыть?",
    },
}

# Explicit Focus troubleshooting. These strings are deliberately historical:
# Focus is read only when the user presses the troubleshooting button, so a
# cached result must never read like continuously monitored current state.
TRANSLATIONS.update({
    "Focus troubleshooting:": {
        "zh-Hans": "专注模式故障排查：", "zh-Hant": "專注模式疑難排解：",
        "ja": "集中モードのトラブルシューティング：", "ko": "집중 모드 문제 해결:",
        "fr": "Dépannage de Concentration :", "es": "Diagnóstico de Concentración:",
        "hi": "फ़ोकस समस्या निवारण:", "ru": "Диагностика фокусирования:",
        "de": "Fokus-Fehlerbehebung:", "pt-BR": "Solução de problemas do Foco:",
        "it": "Risoluzione problemi Full immersion:",
    },
    "Check Focus Blocking…": {
        "zh-Hans": "检查专注模式阻止…", "zh-Hant": "檢查專注模式阻擋…",
        "ja": "集中モードのブロックを確認…", "ko": "집중 모드 차단 확인…",
        "fr": "Vérifier le blocage par Concentration…", "es": "Comprobar bloqueo de Concentración…",
        "hi": "फ़ोकस अवरोध जाँचें…", "ru": "Проверить блокировку фокусированием…",
        "de": "Fokus-Blockierung prüfen…", "pt-BR": "Verificar bloqueio pelo Foco…",
        "it": "Verifica blocco di Full immersion…",
    },
    "Check Again…": {
        "zh-Hans": "再次检查…", "zh-Hant": "再次檢查…", "ja": "もう一度確認…",
        "ko": "다시 확인…", "fr": "Vérifier à nouveau…", "es": "Comprobar de nuevo…",
        "hi": "फिर से जाँचें…", "ru": "Проверить снова…", "de": "Erneut prüfen…",
        "pt-BR": "Verificar novamente…", "it": "Verifica di nuovo…",
    },
    "Checking Focus…": {
        "zh-Hans": "正在检查专注模式…", "zh-Hant": "正在檢查專注模式…",
        "ja": "集中モードを確認中…", "ko": "집중 모드 확인 중…",
        "fr": "Vérification de Concentration…", "es": "Comprobando Concentración…",
        "hi": "फ़ोकस की जाँच हो रही है…", "ru": "Проверка фокусирования…",
        "de": "Fokus wird geprüft…", "pt-BR": "Verificando Foco…",
        "it": "Verifica di Full immersion…",
    },
    "Focus is checked only when you press the troubleshooting button. Laban never reads or requests Focus Status during launch or normal notification delivery.": {
        "zh-Hans": "仅在您按下故障排查按钮时检查专注模式。Laban 在启动或正常发送通知期间绝不会读取或请求专注模式状态。",
        "zh-Hant": "僅在您按下疑難排解按鈕時檢查專注模式。Laban 在啟動或正常傳送通知期間絕不會讀取或要求專注模式狀態。",
        "ja": "集中モードは、トラブルシューティングボタンを押したときだけ確認されます。Laban は起動時や通常の通知配信時に集中モード状況を読み取ったり要求したりしません。",
        "ko": "집중 모드는 문제 해결 버튼을 누를 때만 확인됩니다. Laban은 실행 또는 일반 알림 전달 중에 집중 모드 상태를 읽거나 요청하지 않습니다.",
        "fr": "Concentration n’est vérifiée que lorsque vous appuyez sur le bouton de dépannage. Laban ne lit ni ne demande jamais l’état de Concentration au lancement ou lors de l’envoi normal des notifications.",
        "es": "Concentración solo se comprueba al pulsar el botón de diagnóstico. Laban nunca lee ni solicita el estado de Concentración durante el inicio o la entrega normal de notificaciones.",
        "hi": "फ़ोकस केवल समस्या निवारण बटन दबाने पर जाँचा जाता है। Laban लॉन्च या सामान्य सूचना वितरण के दौरान फ़ोकस स्थिति को कभी पढ़ता या माँगता नहीं है।",
        "ru": "Фокусирование проверяется только после нажатия кнопки диагностики. Laban никогда не читает и не запрашивает статус фокусирования при запуске или обычной доставке уведомлений.",
        "de": "Der Fokus wird nur geprüft, wenn Sie die Fehlerbehebungstaste drücken. Laban liest oder fordert den Fokusstatus weder beim Start noch bei der normalen Benachrichtigungszustellung an.",
        "pt-BR": "O Foco só é verificado quando você pressiona o botão de solução de problemas. O Laban nunca lê nem solicita o Estado de Foco durante a inicialização ou a entrega normal de notificações.",
        "it": "Full immersion viene controllata solo quando premi il pulsante di risoluzione dei problemi. Laban non legge né richiede mai lo stato di Full immersion all’avvio o durante il normale recapito delle notifiche.",
    },
    "Checks whether the current Focus is silencing Laban. The first check may ask for Focus Status permission.": {
        "zh-Hans": "检查当前专注模式是否将 Laban 静音。首次检查可能会请求专注模式状态权限。",
        "zh-Hant": "檢查目前專注模式是否將 Laban 靜音。首次檢查可能會要求專注模式狀態權限。",
        "ja": "現在の集中モードが Laban を通知オフにしているか確認します。初回の確認では集中モード状況の許可を求める場合があります。",
        "ko": "현재 집중 모드가 Laban 알림을 끄고 있는지 확인합니다. 첫 확인 시 집중 모드 상태 권한을 요청할 수 있습니다.",
        "fr": "Vérifie si le mode Concentration actuel réduit Laban au silence. La première vérification peut demander l’autorisation d’accéder à l’état de Concentration.",
        "es": "Comprueba si el modo Concentración actual silencia Laban. La primera comprobación puede solicitar permiso para el estado de Concentración.",
        "hi": "जाँचता है कि वर्तमान फ़ोकस Laban को शांत कर रहा है या नहीं। पहली जाँच फ़ोकस स्थिति की अनुमति माँग सकती है।",
        "ru": "Проверяет, заглушает ли текущий режим фокусирования Laban. При первой проверке может потребоваться разрешение на статус фокусирования.",
        "de": "Prüft, ob der aktuelle Fokus Laban stummschaltet. Bei der ersten Prüfung kann die Berechtigung für den Fokusstatus angefordert werden.",
        "pt-BR": "Verifica se o Foco atual está silenciando o Laban. A primeira verificação pode solicitar permissão para o Estado de Foco.",
        "it": "Controlla se Full immersion sta silenziando Laban. Il primo controllo potrebbe richiedere l’autorizzazione per lo stato di Full immersion.",
    },
    "Troubleshooting only: check whether the current Focus is silencing Laban. This may ask for Focus Status permission.": {
        "zh-Hans": "仅用于故障排查：检查当前专注模式是否将 Laban 静音。这可能会请求专注模式状态权限。",
        "zh-Hant": "僅用於疑難排解：檢查目前專注模式是否將 Laban 靜音。這可能會要求專注模式狀態權限。",
        "ja": "トラブルシューティング専用：現在の集中モードが Laban を通知オフにしているか確認します。集中モード状況の許可を求める場合があります。",
        "ko": "문제 해결 전용: 현재 집중 모드가 Laban 알림을 끄고 있는지 확인합니다. 집중 모드 상태 권한을 요청할 수 있습니다.",
        "fr": "Dépannage uniquement : vérifiez si le mode Concentration actuel réduit Laban au silence. Une autorisation d’accès à l’état de Concentration peut être demandée.",
        "es": "Solo para diagnóstico: comprueba si el modo Concentración actual silencia Laban. Puede solicitar permiso para el estado de Concentración.",
        "hi": "केवल समस्या निवारण: जाँचें कि वर्तमान फ़ोकस Laban को शांत कर रहा है या नहीं। यह फ़ोकस स्थिति की अनुमति माँग सकता है।",
        "ru": "Только для диагностики: проверьте, заглушает ли текущий режим фокусирования Laban. Может потребоваться разрешение на статус фокусирования.",
        "de": "Nur zur Fehlerbehebung: Prüfen Sie, ob der aktuelle Fokus Laban stummschaltet. Dabei kann die Berechtigung für den Fokusstatus angefordert werden.",
        "pt-BR": "Somente para solução de problemas: verifique se o Foco atual está silenciando o Laban. Isso pode solicitar permissão para o Estado de Foco.",
        "it": "Solo per la risoluzione dei problemi: controlla se Full immersion sta silenziando Laban. Potrebbe essere richiesta l’autorizzazione per lo stato di Full immersion.",
    },
    "Focus Status permission was not decided, so Laban could not tell whether Focus was silencing notifications.": {
        "zh-Hans": "尚未决定专注模式状态权限，因此 Laban 无法判断专注模式是否将通知静音。",
        "zh-Hant": "尚未決定專注模式狀態權限，因此 Laban 無法判斷專注模式是否將通知靜音。",
        "ja": "集中モード状況の許可が決定されていなかったため、Laban は集中モードが通知をオフにしていたか判断できませんでした。",
        "ko": "집중 모드 상태 권한이 결정되지 않아 Laban은 집중 모드가 알림을 끄고 있었는지 확인할 수 없었습니다.",
        "fr": "L’autorisation d’accès à l’état de Concentration n’était pas définie ; Laban n’a donc pas pu déterminer si Concentration désactivait les notifications.",
        "es": "No se había decidido el permiso para el estado de Concentración, por lo que Laban no pudo determinar si Concentración silenciaba las notificaciones.",
        "hi": "फ़ोकस स्थिति की अनुमति तय नहीं थी, इसलिए Laban यह नहीं बता सका कि फ़ोकस सूचनाओं को शांत कर रहा था या नहीं।",
        "ru": "Разрешение на статус фокусирования не было определено, поэтому Laban не смог установить, заглушало ли фокусирование уведомления.",
        "de": "Die Berechtigung für den Fokusstatus war nicht festgelegt. Daher konnte Laban nicht erkennen, ob der Fokus Benachrichtigungen stummschaltete.",
        "pt-BR": "A permissão para o Estado de Foco não estava definida, então o Laban não pôde saber se o Foco estava silenciando as notificações.",
        "it": "L’autorizzazione per lo stato di Full immersion non era stata decisa, quindi Laban non ha potuto stabilire se le notifiche venivano silenziate.",
    },
    "Focus Status access was restricted, so Laban could not tell whether Focus was silencing notifications.": {
        "zh-Hans": "专注模式状态访问受限，因此 Laban 无法判断专注模式是否将通知静音。",
        "zh-Hant": "專注模式狀態存取受限，因此 Laban 無法判斷專注模式是否將通知靜音。",
        "ja": "集中モード状況へのアクセスが制限されていたため、Laban は集中モードが通知をオフにしていたか判断できませんでした。",
        "ko": "집중 모드 상태 접근이 제한되어 Laban은 집중 모드가 알림을 끄고 있었는지 확인할 수 없었습니다.",
        "fr": "L’accès à l’état de Concentration était restreint ; Laban n’a donc pas pu déterminer si Concentration désactivait les notifications.",
        "es": "El acceso al estado de Concentración estaba restringido, por lo que Laban no pudo determinar si Concentración silenciaba las notificaciones.",
        "hi": "फ़ोकस स्थिति की पहुँच प्रतिबंधित थी, इसलिए Laban यह नहीं बता सका कि फ़ोकस सूचनाओं को शांत कर रहा था या नहीं।",
        "ru": "Доступ к статусу фокусирования был ограничен, поэтому Laban не смог установить, заглушало ли фокусирование уведомления.",
        "de": "Der Zugriff auf den Fokusstatus war eingeschränkt. Daher konnte Laban nicht erkennen, ob der Fokus Benachrichtigungen stummschaltete.",
        "pt-BR": "O acesso ao Estado de Foco estava restrito, então o Laban não pôde saber se o Foco estava silenciando as notificações.",
        "it": "L’accesso allo stato di Full immersion era limitato, quindi Laban non ha potuto stabilire se le notifiche venivano silenziate.",
    },
    "Focus Status access was denied. Enable it in Privacy & Security to let Laban diagnose Focus blocking.": {
        "zh-Hans": "专注模式状态访问被拒绝。请在“隐私与安全性”中启用，以便 Laban 诊断专注模式阻止。",
        "zh-Hant": "專注模式狀態存取遭拒絕。請在「隱私權與安全性」中啟用，以便 Laban 診斷專注模式阻擋。",
        "ja": "集中モード状況へのアクセスが拒否されました。Laban が集中モードによるブロックを診断できるよう、「プライバシーとセキュリティ」で有効にしてください。",
        "ko": "집중 모드 상태 접근이 거부되었습니다. Laban이 집중 모드 차단을 진단할 수 있도록 개인정보 보호 및 보안에서 허용하십시오.",
        "fr": "L’accès à l’état de Concentration a été refusé. Activez-le dans Confidentialité et sécurité pour permettre à Laban de diagnostiquer le blocage.",
        "es": "Se denegó el acceso al estado de Concentración. Actívalo en Privacidad y seguridad para que Laban pueda diagnosticar el bloqueo.",
        "hi": "फ़ोकस स्थिति की पहुँच अस्वीकृत थी। Laban को फ़ोकस अवरोध जाँचने देने के लिए इसे गोपनीयता और सुरक्षा में सक्षम करें।",
        "ru": "Доступ к статусу фокусирования был запрещён. Разрешите его в разделе «Конфиденциальность и безопасность», чтобы Laban мог диагностировать блокировку.",
        "de": "Der Zugriff auf den Fokusstatus wurde verweigert. Aktivieren Sie ihn unter Datenschutz & Sicherheit, damit Laban Fokus-Blockierungen diagnostizieren kann.",
        "pt-BR": "O acesso ao Estado de Foco foi negado. Ative-o em Privacidade e Segurança para o Laban diagnosticar o bloqueio pelo Foco.",
        "it": "L’accesso allo stato di Full immersion è stato negato. Abilitalo in Privacy e sicurezza per consentire a Laban di diagnosticare il blocco.",
    },
    "Focus was silencing Laban notifications. Add Laban to the active Focus's Allowed Apps.": {
        "zh-Hans": "专注模式正在将 Laban 通知静音。请将 Laban 添加到当前专注模式的允许 App。",
        "zh-Hant": "專注模式正在將 Laban 通知靜音。請將 Laban 加入目前專注模式的允許 App。",
        "ja": "集中モードが Laban の通知をオフにしていました。Laban を有効な集中モードの許可されたアプリに追加してください。",
        "ko": "집중 모드가 Laban 알림을 끄고 있었습니다. Laban을 활성 집중 모드의 허용된 앱에 추가하십시오.",
        "fr": "Concentration désactivait les notifications de Laban. Ajoutez Laban aux apps autorisées du mode actif.",
        "es": "Concentración silenciaba las notificaciones de Laban. Añade Laban a las apps permitidas del modo activo.",
        "hi": "फ़ोकस Laban की सूचनाओं को शांत कर रहा था। Laban को सक्रिय फ़ोकस के अनुमत ऐप्स में जोड़ें।",
        "ru": "Фокусирование заглушало уведомления Laban. Добавьте Laban в разрешённые приложения активного режима.",
        "de": "Der Fokus schaltete Laban-Benachrichtigungen stumm. Fügen Sie Laban den erlaubten Apps des aktiven Fokus hinzu.",
        "pt-BR": "O Foco estava silenciando as notificações do Laban. Adicione o Laban aos apps permitidos do Foco ativo.",
        "it": "Full immersion silenziava le notifiche di Laban. Aggiungi Laban alle app consentite della modalità attiva.",
    },
    "Focus was not silencing Laban notifications.": {
        "zh-Hans": "专注模式未将 Laban 通知静音。", "zh-Hant": "專注模式未將 Laban 通知靜音。",
        "ja": "集中モードは Laban の通知をオフにしていませんでした。", "ko": "집중 모드가 Laban 알림을 끄고 있지 않았습니다.",
        "fr": "Concentration ne désactivait pas les notifications de Laban.", "es": "Concentración no silenciaba las notificaciones de Laban.",
        "hi": "फ़ोकस Laban की सूचनाओं को शांत नहीं कर रहा था।", "ru": "Фокусирование не заглушало уведомления Laban.",
        "de": "Der Fokus schaltete Laban-Benachrichtigungen nicht stumm.", "pt-BR": "O Foco não estava silenciando as notificações do Laban.",
        "it": "Full immersion non silenziava le notifiche di Laban.",
    },
    "Focus Status access was authorized, but macOS did not provide a result for this build.": {
        "zh-Hans": "已授权专注模式状态访问，但 macOS 未为此构建提供结果。", "zh-Hant": "已授權專注模式狀態存取，但 macOS 未為此版本提供結果。",
        "ja": "集中モード状況へのアクセスは許可されていましたが、macOS はこのビルドの結果を返しませんでした。", "ko": "집중 모드 상태 접근은 승인되었지만 macOS가 이 빌드에 대한 결과를 제공하지 않았습니다.",
        "fr": "L’accès à l’état de Concentration était autorisé, mais macOS n’a fourni aucun résultat pour cette version.", "es": "El acceso al estado de Concentración estaba autorizado, pero macOS no proporcionó un resultado para esta compilación.",
        "hi": "फ़ोकस स्थिति की पहुँच अधिकृत थी, लेकिन macOS ने इस बिल्ड के लिए परिणाम नहीं दिया।", "ru": "Доступ к статусу фокусирования был разрешён, но macOS не предоставила результат для этой сборки.",
        "de": "Der Zugriff auf den Fokusstatus war autorisiert, aber macOS lieferte für diesen Build kein Ergebnis.", "pt-BR": "O acesso ao Estado de Foco estava autorizado, mas o macOS não forneceu um resultado para esta versão.",
        "it": "L’accesso allo stato di Full immersion era autorizzato, ma macOS non ha fornito un risultato per questa build.",
    },
    "Focus troubleshooting was unavailable in this build.": {
        "zh-Hans": "此构建中无法使用专注模式故障排查。", "zh-Hant": "此版本中無法使用專注模式疑難排解。",
        "ja": "このビルドでは集中モードのトラブルシューティングを利用できませんでした。", "ko": "이 빌드에서는 집중 모드 문제 해결을 사용할 수 없었습니다.",
        "fr": "Le dépannage de Concentration n’était pas disponible dans cette version.", "es": "El diagnóstico de Concentración no estaba disponible en esta compilación.",
        "hi": "इस बिल्ड में फ़ोकस समस्या निवारण उपलब्ध नहीं था।", "ru": "Диагностика фокусирования была недоступна в этой сборке.",
        "de": "Die Fokus-Fehlerbehebung war in diesem Build nicht verfügbar.", "pt-BR": "A solução de problemas do Foco não estava disponível nesta versão.",
        "it": "La risoluzione dei problemi di Full immersion non era disponibile in questa build.",
    },
    "macOS returned an unknown Focus Status authorization state, so Laban could not diagnose Focus blocking.": {
        "zh-Hans": "macOS 返回了未知的专注模式状态授权状态，因此 Laban 无法诊断专注模式阻止。", "zh-Hant": "macOS 傳回未知的專注模式狀態授權狀態，因此 Laban 無法診斷專注模式阻擋。",
        "ja": "macOS が不明な集中モード状況の許可状態を返したため、Laban は集中モードによるブロックを診断できませんでした。", "ko": "macOS가 알 수 없는 집중 모드 상태 권한 상태를 반환하여 Laban이 집중 모드 차단을 진단할 수 없었습니다.",
        "fr": "macOS a renvoyé un état d’autorisation de Concentration inconnu ; Laban n’a donc pas pu diagnostiquer le blocage.", "es": "macOS devolvió un estado de autorización de Concentración desconocido, por lo que Laban no pudo diagnosticar el bloqueo.",
        "hi": "macOS ने अज्ञात फ़ोकस स्थिति अनुमति लौटाई, इसलिए Laban फ़ोकस अवरोध का निदान नहीं कर सका।", "ru": "macOS вернула неизвестное состояние разрешения на статус фокусирования, поэтому Laban не смог диагностировать блокировку.",
        "de": "macOS lieferte einen unbekannten Berechtigungsstatus. Daher konnte Laban die Fokus-Blockierung nicht diagnostizieren.", "pt-BR": "O macOS retornou um estado de autorização desconhecido, então o Laban não pôde diagnosticar o bloqueio pelo Foco.",
        "it": "macOS ha restituito uno stato di autorizzazione sconosciuto, quindi Laban non ha potuto diagnosticare il blocco.",
    },
    "At the last check (%@): %@": {
        "zh-Hans": "上次检查时（%@）：%@", "zh-Hant": "上次檢查時（%@）：%@",
        "ja": "前回の確認時（%@）：%@", "ko": "마지막 확인 시(%@): %@",
        "fr": "Lors de la dernière vérification (%@) : %@", "es": "En la última comprobación (%@): %@",
        "hi": "पिछली जाँच (%@) में: %@", "ru": "При последней проверке (%@): %@",
        "de": "Bei der letzten Prüfung (%@): %@", "pt-BR": "Na última verificação (%@): %@",
        "it": "All’ultimo controllo (%@): %@",
    },
    "Open Focus Status Privacy": {
        "zh-Hans": "打开专注模式状态隐私设置", "zh-Hant": "開啟專注模式狀態隱私權設定",
        "ja": "集中モード状況のプライバシーを開く", "ko": "집중 모드 상태 개인정보 보호 열기",
        "fr": "Ouvrir la confidentialité de Concentration", "es": "Abrir privacidad del estado de Concentración",
        "hi": "फ़ोकस स्थिति गोपनीयता खोलें", "ru": "Открыть конфиденциальность статуса фокусирования",
        "de": "Datenschutz für Fokusstatus öffnen", "pt-BR": "Abrir privacidade do Estado de Foco",
        "it": "Apri privacy stato Full immersion",
    },
    "Open Focus Settings": {
        "zh-Hans": "打开专注模式设置", "zh-Hant": "開啟專注模式設定", "ja": "集中モード設定を開く",
        "ko": "집중 모드 설정 열기", "fr": "Ouvrir les réglages de Concentration", "es": "Abrir ajustes de Concentración",
        "hi": "फ़ोकस सेटिंग्स खोलें", "ru": "Открыть настройки фокусирования", "de": "Fokus-Einstellungen öffnen",
        "pt-BR": "Abrir ajustes de Foco", "it": "Apri impostazioni Full immersion",
    },
    "Open Privacy & Security > Focus to grant Laban Focus Status access.": {
        "zh-Hans": "打开“隐私与安全性”>“专注模式”，向 Laban 授予专注模式状态访问权限。", "zh-Hant": "開啟「隱私權與安全性」>「專注模式」，授予 Laban 專注模式狀態存取權。",
        "ja": "「プライバシーとセキュリティ」>「集中モード」を開き、Laban に集中モード状況へのアクセスを許可します。", "ko": "개인정보 보호 및 보안 > 집중 모드를 열어 Laban에 집중 모드 상태 접근을 허용합니다.",
        "fr": "Ouvrez Confidentialité et sécurité > Concentration pour accorder à Laban l’accès à l’état de Concentration.", "es": "Abre Privacidad y seguridad > Concentración para conceder a Laban acceso al estado de Concentración.",
        "hi": "Laban को फ़ोकस स्थिति की पहुँच देने के लिए गोपनीयता और सुरक्षा > फ़ोकस खोलें।", "ru": "Откройте «Конфиденциальность и безопасность» > «Фокусирование», чтобы предоставить Laban доступ к статусу.",
        "de": "Öffnen Sie Datenschutz & Sicherheit > Fokus, um Laban Zugriff auf den Fokusstatus zu gewähren.", "pt-BR": "Abra Privacidade e Segurança > Foco para conceder ao Laban acesso ao Estado de Foco.",
        "it": "Apri Privacy e sicurezza > Full immersion per consentire a Laban di accedere allo stato.",
    },
    "Open Focus settings to add Laban to the active Focus's Allowed Apps.": {
        "zh-Hans": "打开专注模式设置，将 Laban 添加到当前专注模式的允许 App。", "zh-Hant": "開啟專注模式設定，將 Laban 加入目前專注模式的允許 App。",
        "ja": "集中モード設定を開き、Laban を有効な集中モードの許可されたアプリに追加します。", "ko": "집중 모드 설정을 열어 Laban을 활성 집중 모드의 허용된 앱에 추가합니다.",
        "fr": "Ouvrez les réglages de Concentration pour ajouter Laban aux apps autorisées du mode actif.", "es": "Abre los ajustes de Concentración para añadir Laban a las apps permitidas del modo activo.",
        "hi": "Laban को सक्रिय फ़ोकस के अनुमत ऐप्स में जोड़ने के लिए फ़ोकस सेटिंग्स खोलें।", "ru": "Откройте настройки фокусирования, чтобы добавить Laban в разрешённые приложения активного режима.",
        "de": "Öffnen Sie die Fokus-Einstellungen, um Laban den erlaubten Apps des aktiven Fokus hinzuzufügen.", "pt-BR": "Abra os ajustes de Foco para adicionar o Laban aos apps permitidos do Foco ativo.",
        "it": "Apri le impostazioni di Full immersion per aggiungere Laban alle app consentite della modalità attiva.",
    },
    FOCUS_STATUS_USAGE_DESCRIPTION: {
        "zh-Hans": "当您明确运行专注模式故障排查时，Laban 会检查当前专注模式是否将终端提醒通知静音。", "zh-Hant": "當您明確執行專注模式疑難排解時，Laban 會檢查啟用中的專注模式是否將終端機提醒通知靜音。",
        "ja": "集中モードのトラブルシューティングを明示的に実行したとき、Laban は有効な集中モードがターミナルの注意通知をオフにしているか確認します。", "ko": "집중 모드 문제 해결을 명시적으로 실행하면 Laban은 활성 집중 모드가 터미널 주의 알림을 끄고 있는지 확인합니다.",
        "fr": "Lorsque vous lancez explicitement le dépannage de Concentration, Laban vérifie si un mode actif réduit au silence les notifications d’attention du terminal.", "es": "Cuando ejecutas explícitamente el diagnóstico de Concentración, Laban comprueba si un modo activo silencia las notificaciones de atención del terminal.",
        "hi": "जब आप स्पष्ट रूप से फ़ोकस समस्या निवारण चलाते हैं, तो Laban जाँचता है कि सक्रिय फ़ोकस टर्मिनल ध्यान सूचनाओं को शांत कर रहा है या नहीं।", "ru": "Когда вы явно запускаете диагностику фокусирования, Laban проверяет, заглушает ли активный режим уведомления терминала.",
        "de": "Wenn Sie die Fokus-Fehlerbehebung ausdrücklich ausführen, prüft Laban, ob ein aktiver Fokus Terminal-Benachrichtigungen stummschaltet.", "pt-BR": "Quando você executa explicitamente a solução de problemas do Foco, o Laban verifica se um Foco ativo está silenciando as notificações de atenção do terminal.",
        "it": "Quando avvii esplicitamente la risoluzione dei problemi di Full immersion, Laban controlla se una modalità attiva silenzia le notifiche di attenzione del terminale.",
    },
})


def build_xcstrings() -> dict:
    strings: dict = {}
    for source, locales in TRANSLATIONS.items():
        entry: dict = {"localizations": {}}
        merged = {**locales, **SUPPLEMENT_DE_PT_IT.get(source, {})}
        for locale in LOCALES:
            value = merged.get(locale)
            if value is None:
                continue
            entry["localizations"][locale] = {
                "stringUnit": {"state": "translated", "value": value}
            }
        strings[source] = entry
    return {
        "sourceLanguage": "en",
        "strings": strings,
        "version": "1.0",
    }


def localized_value(source: str, locale: str) -> str:
    if locale == "en":
        return source
    locales = {
        **TRANSLATIONS.get(source, {}),
        **SUPPLEMENT_DE_PT_IT.get(source, {}),
    }
    return locales.get(locale, source)


def write_focus_info_plist_strings(resources: Path) -> None:
    for locale in ("en", *LOCALES):
        value = localized_value(FOCUS_STATUS_USAGE_DESCRIPTION, locale)
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        destination = resources / f"{locale}.lproj" / "InfoPlist.strings"
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            f'"NSFocusStatusUsageDescription" = "{escaped}";\n',
            encoding="utf-8",
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="verify that the committed string catalog matches generated output without writing",
    )
    mode.add_argument("--focus-usage-description", metavar="LOCALE")
    mode.add_argument("--write-focus-info-plist-strings", type=Path, metavar="RESOURCES")
    args = parser.parse_args()

    if args.focus_usage_description:
        print(localized_value(FOCUS_STATUS_USAGE_DESCRIPTION, args.focus_usage_description))
        return
    if args.write_focus_info_plist_strings:
        write_focus_info_plist_strings(args.write_focus_info_plist_strings)
        return

    generated = json.dumps(build_xcstrings(), ensure_ascii=False, indent=2) + "\n"
    if args.check:
        try:
            committed = OUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated catalog: {OUT}", file=sys.stderr)
            raise SystemExit(1)
        if committed != generated:
            print(
                "Localizable.xcstrings is out of date; "
                "run python3 scripts/gen-localizable-xcstrings.py",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"verified {OUT} ({len(TRANSLATIONS)} strings)")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT} ({len(TRANSLATIONS)} strings)")


if __name__ == "__main__":
    main()
