#!/usr/bin/env python3
"""Generate the TraceReuseData TLA+ module from labpty reuse traces.

trace_reuse.c emits one NDJSON record per registry lifecycle transition:

    {"action": "...", "used": [0/1 per slot], "alive": [0/1 per slot],
     "cp": [0/1 per slot], "lid": ["<id>"|"none" per slot]}

Each input file is one daemon run (one seed). This emits a TraceReuseData
module holding every run as a sequence of sequences of per-slot records, plus
the model constants:

    TraceMaxSessions == <slots>
    TraceIds         == { the distinct non-"none" logical_ids seen }
    Traces == << << [used |-> <<..>>, alive |-> <<..>>, cp |-> <<..>>,
                     lid |-> <<"a","none",..>>], ... >>, << ... >> >>

specs/labpty/TraceReuse.tla reconstructs LabptyReuse's `sessions` from each
record and replays the run against LabptyReuse (Fixed = TRUE).

Usage: gen-reuse-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]
"""
import json
import sys


def seq_int(vals):
    return "<<" + ", ".join(str(int(v)) for v in vals) + ">>"


def seq_str(vals):
    return "<<" + ", ".join('"' + v + '"' for v in vals) + ">>"


def load(path):
    recs = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                recs.append(json.loads(line))
    if not recs:
        sys.exit(f"gen-reuse-tla.py: {path} is empty")
    return recs


def render(r):
    return ('[action |-> "{act}", used |-> {u}, alive |-> {a}, '
            "cp |-> {c}, lid |-> {l}]").format(
        act=r["action"], u=seq_int(r["used"]), a=seq_int(r["alive"]),
        c=seq_int(r["cp"]), l=seq_str(r["lid"]))


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gen-reuse-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]")
    out_path = sys.argv[1]
    traces = [load(p) for p in sys.argv[2:]]

    n_slots = len(traces[0][0]["used"])
    ids = sorted({v for t in traces for r in t for v in r["lid"] if v != "none"})

    blocks = []
    for recs in traces:
        rows = ",\n".join("      " + render(r) for r in recs)
        blocks.append("    <<\n" + rows + "\n    >>")

    ids_set = "{" + ", ".join('"' + i + '"' for i in ids) + "}"
    out = []
    out.append("---------------------------- MODULE TraceReuseData ----------------------------")
    out.append("\\* GENERATED by scripts/gen-reuse-tla.py from labpty reuse traces.")
    out.append("\\* Do not edit; regenerated on every scripts/check-trace run.")
    out.append("EXTENDS Naturals")
    out.append("")
    out.append(f"TraceMaxSessions == {n_slots}")
    out.append(f"TraceIds == {ids_set}")
    out.append("")
    out.append("Traces == <<")
    out.append(",\n".join(blocks))
    out.append(">>")
    out.append("")
    out.append("=============================================================================")
    with open(out_path, "w") as fh:
        fh.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
