#!/usr/bin/env python3
"""Generate the TraceData TLA+ module from labpty attachment traces.

The daemon's labpty_trace_emit writes one NDJSON record per attachment
transition:

    {"action": "...", "inUse": [0/1 per client],
     "alive": [0/1 per session], "attached": [[client ids] per session]}

Each input file is one daemon run (one seed). This emits a TraceData module
holding every run as a sequence of sequences:

    Traces == << << [inUse |-> {set}, alive |-> {set}, attached |-> <fn>], ... >>,
                 << ... >> >>

so specs/labpty/TraceAttachment.tla replays all of them in a single TLC run
(it picks a trace index nondeterministically at Init). inUse/alive are sets of
live indices; attached is a function from session id to its attached client
set (empty sessions omitted).

Usage: gen-trace-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]
"""
import json
import sys


def tla_set(ids):
    return "{" + ", ".join(str(i) for i in ids) + "}"


def tla_attached(attached):
    parts = [(s, lst) for s, lst in enumerate(attached) if lst]
    if not parts:
        return "[s \\in {} |-> {}]"  # empty-domain function
    return "(" + " @@ ".join(f"{s} :> {tla_set(lst)}" for s, lst in parts) + ")"


def load_trace(path):
    records = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    if not records:
        sys.exit(f"gen-trace-tla.py: {path} is empty")
    return records


def render_record(r):
    inuse = tla_set([c for c, v in enumerate(r["inUse"]) if v])
    alive = tla_set([s for s, v in enumerate(r["alive"]) if v])
    att = tla_attached(r["attached"])
    return (f'[action |-> "{r["action"]}", inUse |-> {inuse}, '
            f"alive |-> {alive}, attached |-> {att}]")


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gen-trace-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]")
    out_path = sys.argv[1]
    inputs = sys.argv[2:]

    traces = [load_trace(p) for p in inputs]
    n_clients = len(traces[0][0]["inUse"])
    n_sessions = len(traces[0][0]["alive"])

    trace_blocks = []
    for records in traces:
        rows = ",\n".join("      " + render_record(r) for r in records)
        trace_blocks.append("    <<\n" + rows + "\n    >>")

    out = []
    out.append("------------------------------ MODULE TraceData ------------------------------")
    out.append("\\* GENERATED by scripts/gen-trace-tla.py from labpty attachment traces.")
    out.append("\\* Do not edit; regenerated on every scripts/check-trace run.")
    out.append("EXTENDS TLC, Naturals")
    out.append("")
    out.append(f"TraceClients  == 0..{n_clients - 1}")
    out.append(f"TraceSessions == 0..{n_sessions - 1}")
    out.append("")
    out.append("Traces == <<")
    out.append(",\n".join(trace_blocks))
    out.append(">>")
    out.append("")
    out.append("=============================================================================")
    text = "\n".join(out) + "\n"

    with open(out_path, "w") as fh:
        fh.write(text)


if __name__ == "__main__":
    main()
