#!/usr/bin/env python3
"""Generate the TraceControlData TLA+ module from labpty control-channel traces.

trace_control.c emits one NDJSON record per control-channel transition:

    {"action": "...", "clients": [{"state","in_use","negotiated","established"}, ...]}

Each input file is one daemon run (one seed). This emits a TraceControlData
module holding every run as a sequence of sequences of per-client records:

    TraceClients == 1..N
    Traces == << << [action |-> "...", clients |-> << [state |-> "idle",
                     in_use |-> 1, negotiated |-> 0, established |-> 0], ... >>],
                 ... >>, << ... >> >>

specs/labpty/TraceControlChannel.tla replays each run against
LabptyControlChannel, pinning the four observable fields per client (the
model's frames_issued is a hidden TLC finiteness bound).

Usage: gen-control-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]
"""
import json
import sys


def client_rec(c):
    return ('[state |-> "{s}", in_use |-> {u}, negotiated |-> {n}, '
            "established |-> {e}]").format(
        s=c["state"], u=int(c["in_use"]), n=int(c["negotiated"]),
        e=int(c["established"]))


def render(r):
    clients = ", ".join(client_rec(c) for c in r["clients"])
    return '[action |-> "{a}", clients |-> <<{c}>>]'.format(a=r["action"], c=clients)


def load(path):
    recs = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                recs.append(json.loads(line))
    if not recs:
        sys.exit(f"gen-control-tla.py: {path} is empty")
    return recs


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gen-control-tla.py <out.tla> <run1.ndjson> [run2.ndjson ...]")
    out_path = sys.argv[1]
    traces = [load(p) for p in sys.argv[2:]]
    n_clients = len(traces[0][0]["clients"])

    blocks = []
    for recs in traces:
        rows = ",\n".join("      " + render(r) for r in recs)
        blocks.append("    <<\n" + rows + "\n    >>")

    out = []
    out.append("--------------------------- MODULE TraceControlData ---------------------------")
    out.append("\\* GENERATED by scripts/gen-control-tla.py from labpty control-channel traces.")
    out.append("\\* Do not edit; regenerated on every scripts/check-trace run.")
    out.append("EXTENDS Naturals")
    out.append("")
    out.append(f"TraceClients == 1..{n_clients}")
    out.append("")
    out.append("Traces == <<")
    out.append(",\n".join(blocks))
    out.append(">>")
    out.append("")
    out.append("=============================================================================")
    with open(out_path, "w") as fh:
        fh.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
