#!/usr/bin/env python3
"""Generate Sources/LabanApp/Resources/Localizable.xcstrings from the translation table."""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "Sources/LabanApp/Resources/Localizable.xcstrings"

LOCALES = ("zh-Hans", "zh-Hant", "ja", "ko", "fr", "es", "hi", "ru", "de", "pt-BR", "it")

from importlib.machinery import SourceFileLoader

_supplement_mod = SourceFileLoader(
    "localizable_supplement",
    str(REPO / "scripts/localizable-supplement-de-pt-it.py"),
).load_module()
SUPPLEMENT_DE_PT_IT: dict[str, dict[str, str]] = _supplement_mod.SUPPLEMENT_DE_PT_IT

# English source -> per-locale translations. Keep keys identical to Swift L10n.tr("…") calls.
TRANSLATIONS: dict[str, dict[str, str]] = {
    # App menu
    "About Laban": {
        "zh-Hans": "关于 Laban",
        "zh-Hant": "關於 Laban",
        "ja": "Laban について",
        "ko": "Laban 정보",
        "fr": "À propos de Laban",
        "es": "Acerca de Laban",
        "hi": "Laban के बारे में",
        "ru": "О программе Laban",
    },
    "Check for Updates…": {
        "zh-Hans": "检查更新…",
        "zh-Hant": "檢查更新…",
        "ja": "アップデートを確認…",
        "ko": "업데이트 확인…",
        "fr": "Rechercher des mises à jour…",
        "es": "Buscar actualizaciones…",
        "hi": "अपडेट जाँचें…",
        "ru": "Проверить обновления…",
    },
    "Settings…": {
        "zh-Hans": "设置…",
        "zh-Hant": "設定…",
        "ja": "設定…",
        "ko": "설정…",
        "fr": "Réglages…",
        "es": "Ajustes…",
        "hi": "सेटिंग्स…",
        "ru": "Настройки…",
    },
    "Secure Keyboard Entry": {
        "zh-Hans": "安全键盘输入",
        "zh-Hant": "安全鍵盤輸入",
        "ja": "セキュアキーボード入力",
        "ko": "보안 키보드 입력",
        "fr": "Saisie clavier sécurisée",
        "es": "Entrada de teclado segura",
        "hi": "सुरक्षित कीबोर्ड इनपुट",
        "ru": "Безопасный ввод с клавиатуры",
    },
    "Hide Laban": {
        "zh-Hans": "隐藏 Laban",
        "zh-Hant": "隱藏 Laban",
        "ja": "Laban を隠す",
        "ko": "Laban 숨기기",
        "fr": "Masquer Laban",
        "es": "Ocultar Laban",
        "hi": "Laban छुपाएँ",
        "ru": "Скрыть Laban",
    },
    "Hide Others": {
        "zh-Hans": "隐藏其他",
        "zh-Hant": "隱藏其他",
        "ja": "ほかを隠す",
        "ko": "기타 항목 숨기기",
        "fr": "Masquer les autres",
        "es": "Ocultar otros",
        "hi": "अन्य छुपाएँ",
        "ru": "Скрыть остальные",
    },
    "Show All": {
        "zh-Hans": "全部显示",
        "zh-Hant": "顯示全部",
        "ja": "すべてを表示",
        "ko": "모두 보기",
        "fr": "Tout afficher",
        "es": "Mostrar todo",
        "hi": "सभी दिखाएँ",
        "ru": "Показать все",
    },
    "Restart Laban": {
        "zh-Hans": "重新启动 Laban",
        "zh-Hant": "重新啟動 Laban",
        "ja": "Laban を再起動",
        "ko": "Laban 다시 시작",
        "fr": "Redémarrer Laban",
        "es": "Reiniciar Laban",
        "hi": "Laban पुनः प्रारंभ करें",
        "ru": "Перезапустить Laban",
    },
    "Quit Laban": {
        "zh-Hans": "退出 Laban",
        "zh-Hant": "結束 Laban",
        "ja": "Laban を終了",
        "ko": "Laban 종료",
        "fr": "Quitter Laban",
        "es": "Salir de Laban",
        "hi": "Laban बंद करें",
        "ru": "Выйти из Laban",
    },
    "File": {
        "zh-Hans": "文件",
        "zh-Hant": "檔案",
        "ja": "ファイル",
        "ko": "파일",
        "fr": "Fichier",
        "es": "Archivo",
        "hi": "फ़ाइल",
        "ru": "Файл",
    },
    "New Tab": {
        "zh-Hans": "新建标签页",
        "zh-Hant": "新增標籤頁",
        "ja": "新しいタブ",
        "ko": "새 탭",
        "fr": "Nouvel onglet",
        "es": "Nueva pestaña",
        "hi": "नया टैब",
        "ru": "Новая вкладка",
    },
    "Close Tab": {
        "zh-Hans": "关闭标签页",
        "zh-Hant": "關閉標籤頁",
        "ja": "タブを閉じる",
        "ko": "탭 닫기",
        "fr": "Fermer l’onglet",
        "es": "Cerrar pestaña",
        "hi": "टैब बंद करें",
        "ru": "Закрыть вкладку",
    },
    "Export Last 10 s as Cast": {
        "zh-Hans": "导出最近 10 秒为 Cast",
        "zh-Hant": "匯出最近 10 秒為 Cast",
        "ja": "直近 10 秒を Cast として書き出す",
        "ko": "최근 10초를 Cast로보내기",
        "fr": "Exporter les 10 dernières s en Cast",
        "es": "Exportar los últimos 10 s como Cast",
        "hi": "पिछले 10 सेकंड Cast के रूप में निर्यात करें",
        "ru": "Экспортировать последние 10 с в Cast",
    },
    "Export Recent…": {
        "zh-Hans": "导出最近记录…",
        "zh-Hant": "匯出最近記錄…",
        "ja": "最近の記録を書き出す…",
        "ko": "최근 기록보내기…",
        "fr": "Exporter l’historique récent…",
        "es": "Exportar reciente…",
        "hi": "हालिया निर्यात करें…",
        "ru": "Экспортировать недавнее…",
    },
    "Last 5 s as Cast": {
        "zh-Hans": "最近 5 秒 Cast",
        "zh-Hant": "最近 5 秒 Cast",
        "ja": "直近 5 秒を Cast",
        "ko": "최근 5초 Cast",
        "fr": "5 dernières s en Cast",
        "es": "Últimos 5 s como Cast",
        "hi": "पिछले 5 सेकंड Cast",
        "ru": "Последние 5 с в Cast",
    },
    "Last 10 s as Cast": {
        "zh-Hans": "最近 10 秒 Cast",
        "zh-Hant": "最近 10 秒 Cast",
        "ja": "直近 10 秒を Cast",
        "ko": "최근 10초 Cast",
        "fr": "10 dernières s en Cast",
        "es": "Últimos 10 s como Cast",
        "hi": "पिछले 10 सेकंड Cast",
        "ru": "Последние 10 с в Cast",
    },
    "Last 30 s as Cast": {
        "zh-Hans": "最近 30 秒 Cast",
        "zh-Hant": "最近 30 秒 Cast",
        "ja": "直近 30 秒を Cast",
        "ko": "최근 30초 Cast",
        "fr": "30 dernières s en Cast",
        "es": "Últimos 30 s como Cast",
        "hi": "पिछले 30 सेकंड Cast",
        "ru": "Последние 30 с в Cast",
    },
    "Last 60 s as Cast": {
        "zh-Hans": "最近 60 秒 Cast",
        "zh-Hant": "最近 60 秒 Cast",
        "ja": "直近 60 秒を Cast",
        "ko": "최근 60초 Cast",
        "fr": "60 dernières s en Cast",
        "es": "Últimos 60 s como Cast",
        "hi": "पिछले 60 सेकंड Cast",
        "ru": "Последние 60 с в Cast",
    },
    "Edit": {
        "zh-Hans": "编辑",
        "zh-Hant": "編輯",
        "ja": "編集",
        "ko": "편집",
        "fr": "Édition",
        "es": "Edición",
        "hi": "संपादन",
        "ru": "Правка",
    },
    "Copy": {
        "zh-Hans": "复制",
        "zh-Hant": "複製",
        "ja": "コピー",
        "ko": "복사",
        "fr": "Copier",
        "es": "Copiar",
        "hi": "कॉपी करें",
        "ru": "Копировать",
    },
    "Paste": {
        "zh-Hans": "粘贴",
        "zh-Hant": "貼上",
        "ja": "ペースト",
        "ko": "붙여넣기",
        "fr": "Coller",
        "es": "Pegar",
        "hi": "पेस्ट करें",
        "ru": "Вставить",
    },
    "Select All": {
        "zh-Hans": "全选",
        "zh-Hant": "全選",
        "ja": "すべてを選択",
        "ko": "모두 선택",
        "fr": "Tout sélectionner",
        "es": "Seleccionar todo",
        "hi": "सभी चुनें",
        "ru": "Выбрать все",
    },
    "Quick Look": {
        "zh-Hans": "快速查看",
        "zh-Hant": "快速預覽",
        "ja": "クイックルック",
        "ko": "빠른 보기",
        "fr": "Coup d’œil",
        "es": "Vista rápida",
        "hi": "त्वरित देखें",
        "ru": "Быстрый просмотр",
    },
    "Find…": {
        "zh-Hans": "查找…",
        "zh-Hant": "尋找…",
        "ja": "検索…",
        "ko": "찾기…",
        "fr": "Rechercher…",
        "es": "Buscar…",
        "hi": "खोजें…",
        "ru": "Найти…",
    },
    "View": {
        "zh-Hans": "显示",
        "zh-Hant": "顯示",
        "ja": "表示",
        "ko": "보기",
        "fr": "Présentation",
        "es": "Ver",
        "hi": "दृश्य",
        "ru": "Вид",
    },
    "Bigger Text": {
        "zh-Hans": "放大文字",
        "zh-Hant": "放大文字",
        "ja": "文字を大きく",
        "ko": "글자 크게",
        "fr": "Texte plus grand",
        "es": "Texto más grande",
        "hi": "बड़ा टेक्स्ट",
        "ru": "Увеличить текст",
    },
    "Smaller Text": {
        "zh-Hans": "缩小文字",
        "zh-Hant": "縮小文字",
        "ja": "文字を小さく",
        "ko": "글자 작게",
        "fr": "Texte plus petit",
        "es": "Texto más pequeño",
        "hi": "छोटा टेक्स्ट",
        "ru": "Уменьшить текст",
    },
    "Default Text Size": {
        "zh-Hans": "默认文字大小",
        "zh-Hant": "預設文字大小",
        "ja": "標準の文字サイズ",
        "ko": "기본 글자 크기",
        "fr": "Taille de texte par défaut",
        "es": "Tamaño de texto predeterminado",
        "hi": "डिफ़ॉल्ट टेक्स्ट आकार",
        "ru": "Размер текста по умолчанию",
    },
    "Enter Full Screen": {
        "zh-Hans": "进入全屏幕",
        "zh-Hant": "進入全螢幕",
        "ja": "フルスクリーンにする",
        "ko": "전체 화면 사용",
        "fr": "Passer en plein écran",
        "es": "Pantalla completa",
        "hi": "पूर्ण स्क्रीन में जाएँ",
        "ru": "Войти в полноэкранный режим",
    },
    "Tab": {
        "zh-Hans": "标签页",
        "zh-Hant": "標籤頁",
        "ja": "タブ",
        "ko": "탭",
        "fr": "Onglet",
        "es": "Pestaña",
        "hi": "टैब",
        "ru": "Вкладка",
    },
    "Previous Tab": {
        "zh-Hans": "上一个标签页",
        "zh-Hant": "上一個標籤頁",
        "ja": "前のタブ",
        "ko": "이전 탭",
        "fr": "Onglet précédent",
        "es": "Pestaña anterior",
        "hi": "पिछला टैब",
        "ru": "Предыдущая вкладка",
    },
    "Next Tab": {
        "zh-Hans": "下一个标签页",
        "zh-Hant": "下一個標籤頁",
        "ja": "次のタブ",
        "ko": "다음 탭",
        "fr": "Onglet suivant",
        "es": "Pestaña siguiente",
        "hi": "अगला टैब",
        "ru": "Следующая вкладка",
    },
    "Select Tab %lld": {
        "zh-Hans": "选择标签页 %lld",
        "zh-Hant": "選擇標籤頁 %lld",
        "ja": "タブ %lld を選択",
        "ko": "탭 %lld 선택",
        "fr": "Sélectionner l’onglet %lld",
        "es": "Seleccionar pestaña %lld",
        "hi": "टैब %lld चुनें",
        "ru": "Выбрать вкладку %lld",
    },
    "Select Last Tab": {
        "zh-Hans": "选择最后一个标签页",
        "zh-Hant": "選擇最後一個標籤頁",
        "ja": "最後のタブを選択",
        "ko": "마지막 탭 선택",
        "fr": "Sélectionner le dernier onglet",
        "es": "Seleccionar última pestaña",
        "hi": "अंतिम टैब चुनें",
        "ru": "Выбрать последнюю вкладку",
    },
    "Debug": {
        "zh-Hans": "调试",
        "zh-Hant": "除錯",
        "ja": "デバッグ",
        "ko": "디버그",
        "fr": "Débogage",
        "es": "Depuración",
        "hi": "डिबग",
        "ru": "Отладка",
    },
    "Start PTY Capture": {
        "zh-Hans": "开始 PTY 捕获",
        "zh-Hant": "開始 PTY 擷取",
        "ja": "PTY キャプチャを開始",
        "ko": "PTY 캡처 시작",
        "fr": "Démarrer la capture PTY",
        "es": "Iniciar captura PTY",
        "hi": "PTY कैप्चर शुरू करें",
        "ru": "Начать захват PTY",
    },
    "Stop PTY Capture": {
        "zh-Hans": "停止 PTY 捕获",
        "zh-Hant": "停止 PTY 擷取",
        "ja": "PTY キャプチャを停止",
        "ko": "PTY 캡처 중지",
        "fr": "Arrêter la capture PTY",
        "es": "Detener captura PTY",
        "hi": "PTY कैप्चर रोकें",
        "ru": "Остановить захват PTY",
    },
    "Dump Render Journal": {
        "zh-Hans": "转储渲染日志",
        "zh-Hant": "傾印渲染日誌",
        "ja": "レンダージャーナルを書き出す",
        "ko": "렌더 저널 덤프",
        "fr": "Exporter le journal de rendu",
        "es": "Volcar diario de renderizado",
        "hi": "रेंडर जर्नल डंप करें",
        "ru": "Сбросить журнал рендеринга",
    },
    "Dump Tab Journal": {
        "zh-Hans": "转储标签页日志",
        "zh-Hant": "傾印標籤頁日誌",
        "ja": "タブジャーナルを書き出す",
        "ko": "탭 저널 덤프",
        "fr": "Exporter le journal d’onglet",
        "es": "Volcar diario de pestaña",
        "hi": "टैब जर्नल डंप करें",
        "ru": "Сбросить журнал вкладки",
    },
    "Capture CPU Profile…": {
        "zh-Hans": "捕获 CPU 配置文件…",
        "zh-Hant": "擷取 CPU 設定檔…",
        "ja": "CPU プロファイルを取得…",
        "ko": "CPU 프로파일 캡처…",
        "fr": "Capturer le profil CPU…",
        "es": "Capturar perfil de CPU…",
        "hi": "CPU प्रोफ़ाइल कैप्चर करें…",
        "ru": "Снять профиль CPU…",
    },
    "Start CPU Recording": {
        "zh-Hans": "开始 CPU 录制",
        "zh-Hant": "開始 CPU 錄製",
        "ja": "CPU 記録を開始",
        "ko": "CPU 녹화 시작",
        "fr": "Démarrer l’enregistrement CPU",
        "es": "Iniciar grabación de CPU",
        "hi": "CPU रिकॉर्डिंग शुरू करें",
        "ru": "Начать запись CPU",
    },
    "Stop CPU Recording": {
        "zh-Hans": "停止 CPU 录制",
        "zh-Hant": "停止 CPU 錄製",
        "ja": "CPU 記録を停止",
        "ko": "CPU 녹화 중지",
        "fr": "Arrêter l’enregistrement CPU",
        "es": "Detener grabación de CPU",
        "hi": "CPU रिकॉर्डिंग रोकें",
        "ru": "Остановить запись CPU",
    },
    "Export CPU Profile…": {
        "zh-Hans": "导出 CPU 配置文件…",
        "zh-Hant": "匯出 CPU 設定檔…",
        "ja": "CPU プロファイルを書き出す…",
        "ko": "CPU 프로파일보내기…",
        "fr": "Exporter le profil CPU…",
        "es": "Exportar perfil de CPU…",
        "hi": "CPU प्रोफ़ाइल निर्यात करें…",
        "ru": "Экспортировать профиль CPU…",
    },
    "Send Diagnostics…": {
        "zh-Hans": "发送诊断信息…",
        "zh-Hant": "傳送診斷資訊…",
        "ja": "診断情報を送信…",
        "ko": "진단 정보 보내기…",
        "fr": "Envoyer les diagnostics…",
        "es": "Enviar diagnósticos…",
        "hi": "डायग्नोस्टिक भेजें…",
        "ru": "Отправить диагностику…",
    },
    "Window": {
        "zh-Hans": "窗口",
        "zh-Hant": "視窗",
        "ja": "ウインドウ",
        "ko": "윈도우",
        "fr": "Fenêtre",
        "es": "Ventana",
        "hi": "विंडो",
        "ru": "Окно",
    },
    "Minimize": {
        "zh-Hans": "最小化",
        "zh-Hant": "最小化",
        "ja": "しまう",
        "ko": "축소",
        "fr": "Réduire",
        "es": "Minimizar",
        "hi": "छोटा करें",
        "ru": "Свернуть",
    },
    "Zoom": {
        "zh-Hans": "缩放",
        "zh-Hant": "縮放",
        "ja": "ズーム",
        "ko": "확대/축소",
        "fr": "Zoom",
        "es": "Zoom",
        "hi": "ज़ूम",
        "ru": "Масштаб",
    },
    "Bring All to Front": {
        "zh-Hans": "全部置于前台",
        "zh-Hant": "全部移至最前",
        "ja": "すべてを前面に移動",
        "ko": "모두 앞으로 가져오기",
        "fr": "Tout ramener au premier plan",
        "es": "Traer todo al frente",
        "hi": "सभी को सामने लाएँ",
        "ru": "Вывести все на передний план",
    },
    "Help": {
        "zh-Hans": "帮助",
        "zh-Hant": "輔助說明",
        "ja": "ヘルプ",
        "ko": "도움말",
        "fr": "Aide",
        "es": "Ayuda",
        "hi": "सहायता",
        "ru": "Справка",
    },
    "Reveal Log Folder in Finder": {
        "zh-Hans": "在 Finder 中显示日志文件夹",
        "zh-Hant": "在 Finder 中顯示日誌資料夾",
        "ja": "Finder でログフォルダを表示",
        "ko": "Finder에서 로그 폴더 보기",
        "fr": "Afficher le dossier des journaux dans le Finder",
        "es": "Mostrar carpeta de registros en Finder",
        "hi": "Finder में लॉग फ़ोल्डर दिखाएँ",
        "ru": "Показать папку журналов в Finder",
    },
    # Renderer / backend menus
    "Renderer": {
        "zh-Hans": "渲染器",
        "zh-Hant": "渲染器",
        "ja": "レンダラー",
        "ko": "렌더러",
        "fr": "Moteur de rendu",
        "es": "Motor de renderizado",
        "hi": "रेंडरर",
        "ru": "Рендерер",
    },
    "Software Renderer": {
        "zh-Hans": "软件渲染器",
        "zh-Hant": "軟體渲染器",
        "ja": "ソフトウェアレンダラー",
        "ko": "소프트웨어 렌더러",
        "fr": "Rendu logiciel",
        "es": "Renderizado por software",
        "hi": "सॉफ़्टवेयर रेंडरर",
        "ru": "Программный рендерер",
    },
    "Classic Metal Renderer": {
        "zh-Hans": "经典 Metal 渲染器",
        "zh-Hant": "經典 Metal 渲染器",
        "ja": "クラシック Metal レンダラー",
        "ko": "클래식 Metal 렌더러",
        "fr": "Rendu Metal classique",
        "es": "Renderizado Metal clásico",
        "hi": "क्लासिक Metal रेंडरर",
        "ru": "Классический Metal-рендерер",
    },
    "GPU-driven Renderer": {
        "zh-Hans": "GPU 驱动渲染器",
        "zh-Hant": "GPU 驅動渲染器",
        "ja": "GPU 駆動レンダラー",
        "ko": "GPU 기반 렌더러",
        "fr": "Rendu piloté par GPU",
        "es": "Renderizado por GPU",
        "hi": "GPU-संचालित रेंडरर",
        "ru": "GPU-рендерер",
    },
    "GPU-driven Renderer (requires macOS 26)": {
        "zh-Hans": "GPU 驱动渲染器（需要 macOS 26）",
        "zh-Hant": "GPU 驅動渲染器（需要 macOS 26）",
        "ja": "GPU 駆動レンダラー（macOS 26 が必要）",
        "ko": "GPU 기반 렌더러(macOS 26 필요)",
        "fr": "Rendu piloté par GPU (macOS 26 requis)",
        "es": "Renderizado por GPU (requiere macOS 26)",
        "hi": "GPU-संचालित रेंडरर (macOS 26 आवश्यक)",
        "ru": "GPU-рендерер (требуется macOS 26)",
    },
    "Vector Glyph Renderer": {
        "zh-Hans": "矢量字形渲染器",
        "zh-Hant": "向量字形渲染器",
        "ja": "ベクターグリフレンダラー",
        "ko": "벡터 글리프 렌더러",
        "fr": "Rendu Vector Glyph",
        "es": "Renderizado Vector Glyph",
        "hi": "वेक्टर ग्लिफ़ रेंडरर",
        "ru": "Векторный глиф-рендерер",
    },
    "Slug Glyph Renderer": {
        "zh-Hans": "Slug 字形渲染器",
        "zh-Hant": "Slug 字形渲染器",
        "ja": "Slug グリフレンダラー",
        "ko": "Slug 글리프 렌더러",
        "fr": "Rendu Slug Glyph",
        "es": "Renderizado Slug Glyph",
        "hi": "Slug ग्लिफ़ रेंडरर",
        "ru": "Slug глиф-рендерер",
    },
    "Terminal Sessions": {
        "zh-Hans": "终端会话",
        "zh-Hant": "終端機工作階段",
        "ja": "ターミナルセッション",
        "ko": "터미널 세션",
        "fr": "Sessions de terminal",
        "es": "Sesiones de terminal",
        "hi": "टर्मिनल सत्र",
        "ru": "Сеансы терминала",
    },
    "Local Sessions": {
        "zh-Hans": "本地会话",
        "zh-Hant": "本機工作階段",
        "ja": "ローカルセッション",
        "ko": "로컬 세션",
        "fr": "Sessions locales",
        "es": "Sesiones locales",
        "hi": "स्थानीय सत्र",
        "ru": "Локальные сеансы",
    },
    "Background Sessions": {
        "zh-Hans": "后台会话",
        "zh-Hant": "背景工作階段",
        "ja": "バックグラウンドセッション",
        "ko": "백그라운드 세션",
        "fr": "Sessions en arrière-plan",
        "es": "Sesiones en segundo plano",
        "hi": "पृष्ठभूमि सत्र",
        "ru": "Фоновые сеансы",
    },
    "Detached Sessions": {
        "zh-Hans": "独立会话",
        "zh-Hant": "獨立工作階段",
        "ja": "デタッチセッション",
        "ko": "분리 세션",
        "fr": "Sessions détachées",
        "es": "Sesiones independientes",
        "hi": "अलग सत्र",
        "ru": "Отдельные сеансы",
    },
    "Follow System Appearance": {
        "zh-Hans": "跟随系统外观",
        "zh-Hant": "跟隨系統外觀",
        "ja": "システムの外観に合わせる",
        "ko": "시스템 모양 따르기",
        "fr": "Suivre l’apparence du système",
        "es": "Seguir apariencia del sistema",
        "hi": "सिस्टम दिखावट का पालन करें",
        "ru": "Следовать системной теме",
    },
    # Settings window
    "Laban Settings": {
        "zh-Hans": "Laban 设置",
        "zh-Hant": "Laban 設定",
        "ja": "Laban 設定",
        "ko": "Laban 설정",
        "fr": "Réglages de Laban",
        "es": "Ajustes de Laban",
        "hi": "Laban सेटिंग्स",
        "ru": "Настройки Laban",
    },
    "Follow system appearance": {
        "zh-Hans": "跟随系统外观",
        "zh-Hant": "跟隨系統外觀",
        "ja": "システムの外観に合わせる",
        "ko": "시스템 모양 따르기",
        "fr": "Suivre l’apparence du système",
        "es": "Seguir apariencia del sistema",
        "hi": "सिस्टम दिखावट का पालन करें",
        "ru": "Следовать системной теме",
    },
    "Apply": {
        "zh-Hans": "应用",
        "zh-Hant": "套用",
        "ja": "適用",
        "ko": "적용",
        "fr": "Appliquer",
        "es": "Aplicar",
        "hi": "लागू करें",
        "ru": "Применить",
    },
    "Change…": {
        "zh-Hans": "更改…",
        "zh-Hant": "更改…",
        "ja": "変更…",
        "ko": "변경…",
        "fr": "Modifier…",
        "es": "Cambiar…",
        "hi": "बदलें…",
        "ru": "Изменить…",
    },
    "Choose…": {
        "zh-Hans": "选择…",
        "zh-Hant": "選擇…",
        "ja": "選択…",
        "ko": "선택…",
        "fr": "Choisir…",
        "es": "Elegir…",
        "hi": "चुनें…",
        "ru": "Выбрать…",
    },
    "Restore tabs on launch": {
        "zh-Hans": "启动时恢复标签页",
        "zh-Hant": "啟動時恢復標籤頁",
        "ja": "起動時にタブを復元",
        "ko": "실행 시 탭 복원",
        "fr": "Restaurer les onglets au lancement",
        "es": "Restaurar pestañas al iniciar",
        "hi": "लॉन्च पर टैब पुनर्स्थापित करें",
        "ru": "Восстанавливать вкладки при запуске",
    },
    "Option as Meta": {
        "zh-Hans": "Option 作为 Meta",
        "zh-Hant": "Option 作為 Meta",
        "ja": "Option を Meta として送信",
        "ko": "Option을 Meta로 사용",
        "fr": "Option comme Meta",
        "es": "Option como Meta",
        "hi": "Option को Meta के रूप में",
        "ru": "Option как Meta",
    },
    "Notify when a tab needs action": {
        "zh-Hans": "标签页需要操作时通知",
        "zh-Hant": "標籤頁需要操作時通知",
        "ja": "タブで操作が必要なときに通知",
        "ko": "탭에 조치가 필요할 때 알림",
        "fr": "Notifier quand un onglet requiert une action",
        "es": "Notificar cuando una pestaña requiere acción",
        "hi": "जब टैब को कार्रवाई चाहिए तो सूचित करें",
        "ru": "Уведомлять, когда вкладке нужно действие",
    },
    "Notify when a task completes": {
        "zh-Hans": "任务完成时通知",
        "zh-Hant": "任務完成時通知",
        "ja": "タスク完了時に通知",
        "ko": "작업 완료 시 알림",
        "fr": "Notifier à la fin d’une tâche",
        "es": "Notificar al completar una tarea",
        "hi": "कार्य पूर्ण होने पर सूचित करें",
        "ru": "Уведомлять о завершении задачи",
    },
    "Notify for passive tab attention": {
        "zh-Hans": "被动标签页提醒时通知",
        "zh-Hant": "被動標籤頁提醒時通知",
        "ja": "低優先度のタブ注意を通知",
        "ko": "수동 탭 주의 알림",
        "fr": "Notifier l’attention passive d’un onglet",
        "es": "Notificar atención pasiva de pestaña",
        "hi": "निष्क्रिय टैब ध्यान के लिए सूचित करें",
        "ru": "Уведомлять о пассивном внимании вкладки",
    },
    "Play notification sound": {
        "zh-Hans": "播放通知声音",
        "zh-Hant": "播放通知聲音",
        "ja": "通知音を再生",
        "ko": "알림 소리 재생",
        "fr": "Jouer un son de notification",
        "es": "Reproducir sonido de notificación",
        "hi": "सूचना ध्वनि बजाएँ",
        "ru": "Воспроизводить звук уведомления",
    },
    "Test Native Notification": {
        "zh-Hans": "测试原生通知",
        "zh-Hant": "測試原生通知",
        "ja": "ネイティブ通知をテスト",
        "ko": "네이티브 알림 테스트",
        "fr": "Tester la notification native",
        "es": "Probar notificación nativa",
        "hi": "मूल सूचना परीक्षण",
        "ru": "Тест нативного уведомления",
    },
    "Blink cursor": {
        "zh-Hans": "光标闪烁",
        "zh-Hant": "游標閃爍",
        "ja": "カーソルを点滅",
        "ko": "커서 깜빡임",
        "fr": "Curseur clignotant",
        "es": "Cursor parpadeante",
        "hi": "कर्सर ब्लिंक करें",
        "ru": "Мигающий курсор",
    },
    "Enable sampling profiler (applies on next launch)": {
        "zh-Hans": "启用采样分析器（下次启动时生效）",
        "zh-Hant": "啟用取樣分析器（下次啟動時生效）",
        "ja": "サンプリングプロファイラを有効化（次回起動時に適用）",
        "ko": "샘플링 프로파일러 사용(다음 실행 시 적용)",
        "fr": "Activer le profileur d’échantillonnage (au prochain lancement)",
        "es": "Activar perfilador de muestreo (al próximo inicio)",
        "hi": "सैंपलिंग प्रोफ़ाइलर सक्षम करें (अगले लॉन्च पर लागू)",
        "ru": "Включить профилировщик выборки (при следующем запуске)",
    },
    "Appearance": {
        "zh-Hans": "外观",
        "zh-Hant": "外觀",
        "ja": "外観",
        "ko": "모양",
        "fr": "Apparence",
        "es": "Apariencia",
        "hi": "दिखावट",
        "ru": "Внешний вид",
    },
    "Terminal": {
        "zh-Hans": "终端",
        "zh-Hant": "終端機",
        "ja": "ターミナル",
        "ko": "터미널",
        "fr": "Terminal",
        "es": "Terminal",
        "hi": "टर्मिनल",
        "ru": "Терминал",
    },
    "Rendering": {
        "zh-Hans": "渲染",
        "zh-Hant": "渲染",
        "ja": "レンダリング",
        "ko": "렌더링",
        "fr": "Rendu",
        "es": "Renderizado",
        "hi": "रेंडरिंग",
        "ru": "Рендеринг",
    },
    "Notifications": {
        "zh-Hans": "通知",
        "zh-Hant": "通知",
        "ja": "通知",
        "ko": "알림",
        "fr": "Notifications",
        "es": "Notificaciones",
        "hi": "सूचनाएँ",
        "ru": "Уведомления",
    },
    "Theme:": {
        "zh-Hans": "主题：",
        "zh-Hant": "主題：",
        "ja": "テーマ：",
        "ko": "테마:",
        "fr": "Thème :",
        "es": "Tema:",
        "hi": "थीम:",
        "ru": "Тема:",
    },
    "Font:": {
        "zh-Hans": "字体：",
        "zh-Hant": "字體：",
        "ja": "フォント：",
        "ko": "글꼴:",
        "fr": "Police :",
        "es": "Fuente:",
        "hi": "फ़ॉन्ट:",
        "ru": "Шрифт:",
    },
    "CJK font:": {
        "zh-Hans": "CJK 字体：",
        "zh-Hant": "CJK 字體：",
        "ja": "CJK フォント：",
        "ko": "CJK 글꼴:",
        "fr": "Police CJK :",
        "es": "Fuente CJK:",
        "hi": "CJK फ़ॉन्ट:",
        "ru": "Шрифт CJK:",
    },
    "Cursor:": {
        "zh-Hans": "光标：",
        "zh-Hant": "游標：",
        "ja": "カーソル：",
        "ko": "커서:",
        "fr": "Curseur :",
        "es": "Cursor:",
        "hi": "कर्सर:",
        "ru": "Курсор:",
    },
    "Scroll:": {
        "zh-Hans": "滚动：",
        "zh-Hant": "捲動：",
        "ja": "スクロール：",
        "ko": "스크롤:",
        "fr": "Défilement :",
        "es": "Desplazamiento:",
        "hi": "स्क्रॉल:",
        "ru": "Прокрутка:",
    },
    "Unicode width:": {
        "zh-Hans": "Unicode 宽度：",
        "zh-Hant": "Unicode 寬度：",
        "ja": "Unicode 幅：",
        "ko": "Unicode 너비:",
        "fr": "Largeur Unicode :",
        "es": "Ancho Unicode:",
        "hi": "Unicode चौड़ाई:",
        "ru": "Ширина Unicode:",
    },
    "Sessions:": {
        "zh-Hans": "会话：",
        "zh-Hant": "工作階段：",
        "ja": "セッション：",
        "ko": "세션:",
        "fr": "Sessions :",
        "es": "Sesiones:",
        "hi": "सत्र:",
        "ru": "Сеансы:",
    },
    "Identity:": {
        "zh-Hans": "标识：",
        "zh-Hant": "識別：",
        "ja": "識別：",
        "ko": "식별:",
        "fr": "Identité :",
        "es": "Identidad:",
        "hi": "पहचान:",
        "ru": "Идентичность:",
    },
    "Renderer:": {
        "zh-Hans": "渲染器：",
        "zh-Hant": "渲染器：",
        "ja": "レンダラー：",
        "ko": "렌더러:",
        "fr": "Moteur de rendu :",
        "es": "Motor de renderizado:",
        "hi": "रेंडरर:",
        "ru": "Рендерер:",
    },
    "Emoji rendering:": {
        "zh-Hans": "表情符号渲染：",
        "zh-Hant": "表情符號渲染：",
        "ja": "絵文字レンダリング：",
        "ko": "이모지 렌더링:",
        "fr": "Rendu des emoji :",
        "es": "Renderizado de emoji:",
        "hi": "इमोजी रेंडरिंग:",
        "ru": "Рендеринг эмодзи:",
    },
    "Vector text AA:": {
        "zh-Hans": "矢量文字抗锯齿：",
        "zh-Hant": "向量文字反鋸齒：",
        "ja": "ベクターテキスト AA：",
        "ko": "벡터 텍스트 AA:",
        "fr": "AA texte vectoriel :",
        "es": "AA de texto vectorial:",
        "hi": "वेक्टर टेक्स्ट AA:",
        "ru": "Сглаживание векторного текста:",
    },
    "Overlap:": {
        "zh-Hans": "重叠：",
        "zh-Hant": "重疊：",
        "ja": "オーバーラップ：",
        "ko": "겹침:",
        "fr": "Chevauchement :",
        "es": "Superposición:",
        "hi": "ओवरलैप:",
        "ru": "Перекрытие:",
    },
    "Text weight:": {
        "zh-Hans": "字重：",
        "zh-Hant": "字重：",
        "ja": "文字の太さ：",
        "ko": "글자 굵기:",
        "fr": "Épaisseur du texte :",
        "es": "Peso del texto:",
        "hi": "टेक्स्ट वज़न:",
        "ru": "Толщина текста:",
    },
    "Smooth scroll:": {
        "zh-Hans": "平滑滚动：",
        "zh-Hant": "平滑捲動：",
        "ja": "スムーズスクロール：",
        "ko": "부드러운 스크롤:",
        "fr": "Défilement fluide :",
        "es": "Desplazamiento suave:",
        "hi": "स्मूथ स्क्रॉल:",
        "ru": "Плавная прокрутка:",
    },
    "Thin": {
        "zh-Hans": "细",
        "zh-Hant": "細",
        "ja": "細い",
        "ko": "얇게",
        "fr": "Fin",
        "es": "Fino",
        "hi": "पतला",
        "ru": "Тонкий",
    },
    "Heavy": {
        "zh-Hans": "粗",
        "zh-Hant": "粗",
        "ja": "太い",
        "ko": "굵게",
        "fr": "Épais",
        "es": "Grueso",
        "hi": "मोटा",
        "ru": "Жирный",
    },
    # Settings option values
    "Software": {
        "zh-Hans": "软件",
        "zh-Hant": "軟體",
        "ja": "ソフトウェア",
        "ko": "소프트웨어",
        "fr": "Logiciel",
        "es": "Software",
        "hi": "सॉफ़्टवेयर",
        "ru": "Программный",
    },
    "Classic (Metal)": {
        "zh-Hans": "经典 (Metal)",
        "zh-Hant": "經典 (Metal)",
        "ja": "クラシック (Metal)",
        "ko": "클래식 (Metal)",
        "fr": "Classique (Metal)",
        "es": "Clásico (Metal)",
        "hi": "क्लासिक (Metal)",
        "ru": "Классический (Metal)",
    },
    "GPU-driven (Metal)": {
        "zh-Hans": "GPU 驱动 (Metal)",
        "zh-Hant": "GPU 驅動 (Metal)",
        "ja": "GPU 駆動 (Metal)",
        "ko": "GPU 기반 (Metal)",
        "fr": "Piloté par GPU (Metal)",
        "es": "Por GPU (Metal)",
        "hi": "GPU-संचालित (Metal)",
        "ru": "GPU (Metal)",
    },
    "GPU-driven (requires macOS 26)": {
        "zh-Hans": "GPU 驱动（需要 macOS 26）",
        "zh-Hant": "GPU 驅動（需要 macOS 26）",
        "ja": "GPU 駆動（macOS 26 が必要）",
        "ko": "GPU 기반(macOS 26 필요)",
        "fr": "Piloté par GPU (macOS 26 requis)",
        "es": "Por GPU (requiere macOS 26)",
        "hi": "GPU-संचालित (macOS 26 आवश्यक)",
        "ru": "GPU (требуется macOS 26)",
    },
    "Vector Glyph": {
        "zh-Hans": "矢量字形",
        "zh-Hant": "向量字形",
        "ja": "ベクターグリフ",
        "ko": "벡터 글리프",
        "fr": "Vector Glyph",
        "es": "Vector Glyph",
        "hi": "वेक्टर ग्लिफ़",
        "ru": "Vector Glyph",
    },
    "Slug Glyph": {
        "zh-Hans": "Slug 字形",
        "zh-Hant": "Slug 字形",
        "ja": "Slug グリフ",
        "ko": "Slug 글리프",
        "fr": "Slug Glyph",
        "es": "Slug Glyph",
        "hi": "Slug ग्लिफ़",
        "ru": "Slug Glyph",
    },
    "Local": {
        "zh-Hans": "本地",
        "zh-Hant": "本機",
        "ja": "ローカル",
        "ko": "로컬",
        "fr": "Local",
        "es": "Local",
        "hi": "स्थानीय",
        "ru": "Локальный",
    },
    "Background": {
        "zh-Hans": "后台",
        "zh-Hant": "背景",
        "ja": "バックグラウンド",
        "ko": "백그라운드",
        "fr": "Arrière-plan",
        "es": "Segundo plano",
        "hi": "पृष्ठभूमि",
        "ru": "Фоновый",
    },
    "Detached": {
        "zh-Hans": "独立",
        "zh-Hant": "獨立",
        "ja": "デタッチ",
        "ko": "분리",
        "fr": "Détaché",
        "es": "Independiente",
        "hi": "अलग",
        "ru": "Отдельный",
    },
    "Block": {
        "zh-Hans": "方块",
        "zh-Hant": "方塊",
        "ja": "ブロック",
        "ko": "블록",
        "fr": "Bloc",
        "es": "Bloque",
        "hi": "ब्लॉक",
        "ru": "Блок",
    },
    "Bar": {
        "zh-Hans": "竖线",
        "zh-Hant": "豎線",
        "ja": "バー",
        "ko": "막대",
        "fr": "Barre",
        "es": "Barra",
        "hi": "बार",
        "ru": "Полоса",
    },
    "Underline": {
        "zh-Hans": "下划线",
        "zh-Hant": "底線",
        "ja": "下線",
        "ko": "밑줄",
        "fr": "Souligné",
        "es": "Subrayado",
        "hi": "रेखांकन",
        "ru": "Подчёркивание",
    },
    "Pixel-smooth": {
        "zh-Hans": "像素平滑",
        "zh-Hant": "像素平滑",
        "ja": "ピクセルスムーズ",
        "ko": "픽셀 부드럽게",
        "fr": "Lissage par pixel",
        "es": "Suave por píxel",
        "hi": "पिक्सेल-स्मूथ",
        "ru": "Пиксельное сглаживание",
    },
    "Line-quantized": {
        "zh-Hans": "按行量化",
        "zh-Hant": "按行量化",
        "ja": "行単位",
        "ko": "줄 단위",
        "fr": "Quantifié par ligne",
        "es": "Cuantizado por línea",
        "hi": "पंक्ति-क्वांटाइज़्ड",
        "ru": "Построчная прокрутка",
    },
    "Auto (recommended)": {
        "zh-Hans": "自动（推荐）",
        "zh-Hant": "自動（建議）",
        "ja": "自動（推奨）",
        "ko": "자동(권장)",
        "fr": "Auto (recommandé)",
        "es": "Automático (recomendado)",
        "hi": "स्वचालित (अनुशंसित)",
        "ru": "Авто (рекомендуется)",
    },
    "Prefer grapheme width": {
        "zh-Hans": "优先字素宽度",
        "zh-Hant": "優先字素寬度",
        "ja": "書記素幅を優先",
        "ko": "자소 너비 우선",
        "fr": "Préférer la largeur graphémique",
        "es": "Preferir ancho de grafema",
        "hi": "ग्राफ़ेम चौड़ाई प्राथमिकता",
        "ru": "Предпочитать ширину графемы",
    },
    "Monochrome": {
        "zh-Hans": "单色",
        "zh-Hant": "單色",
        "ja": "モノクロ",
        "ko": "단색",
        "fr": "Monochrome",
        "es": "Monocromo",
        "hi": "मोनोक्रोम",
        "ru": "Монохром",
    },
    "Color": {
        "zh-Hans": "彩色",
        "zh-Hant": "彩色",
        "ja": "カラー",
        "ko": "컬러",
        "fr": "Couleur",
        "es": "Color",
        "hi": "रंग",
        "ru": "Цветной",
    },
    "Grayscale": {
        "zh-Hans": "灰度",
        "zh-Hant": "灰階",
        "ja": "グレースケール",
        "ko": "그레이스케일",
        "fr": "Niveaux de gris",
        "es": "Escala de grises",
        "hi": "ग्रेस्केल",
        "ru": "Оттенки серого",
    },
    "Calibrated": {
        "zh-Hans": "校准",
        "zh-Hant": "校準",
        "ja": "キャリブレーション",
        "ko": "보정",
        "fr": "Calibré",
        "es": "Calibrado",
        "hi": "कैलिब्रेटेड",
        "ru": "Калиброванный",
    },
    "Custom overlap": {
        "zh-Hans": "自定义重叠",
        "zh-Hant": "自訂重疊",
        "ja": "カスタムオーバーラップ",
        "ko": "사용자 겹침",
        "fr": "Chevauchement personnalisé",
        "es": "Superposición personalizada",
        "hi": "कस्टम ओवरलैप",
        "ru": "Пользовательское перекрытие",
    },
    "RGB subpixel": {
        "zh-Hans": "RGB 子像素",
        "zh-Hant": "RGB 子像素",
        "ja": "RGB サブピクセル",
        "ko": "RGB 서브픽셀",
        "fr": "Sous-pixel RGB",
        "es": "Subpíxel RGB",
        "hi": "RGB सबपिक्सेल",
        "ru": "RGB субпиксель",
    },
    "BGR subpixel": {
        "zh-Hans": "BGR 子像素",
        "zh-Hant": "BGR 子像素",
        "ja": "BGR サブピクセル",
        "ko": "BGR 서브픽셀",
        "fr": "Sous-pixel BGR",
        "es": "Subpíxel BGR",
        "hi": "BGR सबपिक्सेल",
        "ru": "BGR субпиксель",
    },
    "Fluid": {
        "zh-Hans": "流畅",
        "zh-Hant": "流暢",
        "ja": "フルイド",
        "ko": "유동",
        "fr": "Fluide",
        "es": "Fluido",
        "hi": "फ़्लुइड",
        "ru": "Плавный",
    },
    "Crisp": {
        "zh-Hans": "清晰",
        "zh-Hant": "清晰",
        "ja": "くっきり",
        "ko": "선명",
        "fr": "Net",
        "es": "Nítido",
        "hi": "क्रिस्प",
        "ru": "Чёткий",
    },
    # Common buttons / alerts
    "OK": {
        "zh-Hans": "好",
        "zh-Hant": "好",
        "ja": "OK",
        "ko": "확인",
        "fr": "OK",
        "es": "Aceptar",
        "hi": "ठीक",
        "ru": "OK",
    },
    "Cancel": {
        "zh-Hans": "取消",
        "zh-Hant": "取消",
        "ja": "キャンセル",
        "ko": "취소",
        "fr": "Annuler",
        "es": "Cancelar",
        "hi": "रद्द करें",
        "ru": "Отменить",
    },
    "Quit": {
        "zh-Hans": "退出",
        "zh-Hant": "結束",
        "ja": "終了",
        "ko": "종료",
        "fr": "Quitter",
        "es": "Salir",
        "hi": "बंद करें",
        "ru": "Выйти",
    },
    "Restart Now": {
        "zh-Hans": "立即重启",
        "zh-Hant": "立即重新啟動",
        "ja": "今すぐ再起動",
        "ko": "지금 다시 시작",
        "fr": "Redémarrer maintenant",
        "es": "Reiniciar ahora",
        "hi": "अभी पुनः प्रारंभ करें",
        "ru": "Перезапустить сейчас",
    },
    "Later": {
        "zh-Hans": "稍后",
        "zh-Hant": "稍後",
        "ja": "あとで",
        "ko": "나중에",
        "fr": "Plus tard",
        "es": "Más tarde",
        "hi": "बाद में",
        "ru": "Позже",
    },
    "Done": {
        "zh-Hans": "完成",
        "zh-Hant": "完成",
        "ja": "完了",
        "ko": "완료",
        "fr": "Terminé",
        "es": "Listo",
        "hi": "पूर्ण",
        "ru": "Готово",
    },
    "Open Settings": {
        "zh-Hans": "打开设置",
        "zh-Hant": "打開設定",
        "ja": "設定を開く",
        "ko": "설정 열기",
        "fr": "Ouvrir les réglages",
        "es": "Abrir ajustes",
        "hi": "सेटिंग्स खोलें",
        "ru": "Открыть настройки",
    },
    "Reveal in Finder": {
        "zh-Hans": "在 Finder 中显示",
        "zh-Hant": "在 Finder 中顯示",
        "ja": "Finder で表示",
        "ko": "Finder에서 보기",
        "fr": "Afficher dans le Finder",
        "es": "Mostrar en Finder",
        "hi": "Finder में दिखाएँ",
        "ru": "Показать в Finder",
    },
    "Notifications are off for Laban": {
        "zh-Hans": "Laban 的通知已关闭",
        "zh-Hant": "Laban 的通知已關閉",
        "ja": "Laban の通知がオフです",
        "ko": "Laban 알림이 꺼져 있습니다",
        "fr": "Les notifications sont désactivées pour Laban",
        "es": "Las notificaciones están desactivadas para Laban",
        "hi": "Laban के लिए सूचनाएँ बंद हैं",
        "ru": "Уведомления для Laban отключены",
    },
    "Enable Laban in System Settings > Notifications, and choose Banners or Alerts, to receive tab attention notifications.": {
        "zh-Hans": "在系统设置 > 通知中启用 Laban，并选择横幅或提醒，以接收标签页提醒通知。",
        "zh-Hant": "在系統設定 > 通知中啟用 Laban，並選擇橫幅或提醒，以接收標籤頁提醒通知。",
        "ja": "システム設定 > 通知で Laban を有効にし、バナーまたはアラートを選択してタブ注意通知を受け取ります。",
        "ko": "시스템 설정 > 알림에서 Laban을 켜고 배너 또는 알림을 선택해 탭 주의 알림을 받으세요.",
        "fr": "Activez Laban dans Réglages système > Notifications et choisissez Bannières ou Alertes pour recevoir les notifications d’onglet.",
        "es": "Activa Laban en Ajustes del sistema > Notificaciones y elige Banners o Alertas para recibir notificaciones de pestaña.",
        "hi": "सिस्टम सेटिंग्स > सूचनाएँ में Laban सक्षम करें और टैब ध्यान सूचनाएँ पाने के लिए बैनर या अलर्ट चुनें।",
        "ru": "Включите Laban в Системных настройках > Уведомления и выберите Баннеры или Оповещения для уведомлений о вкладках.",
    },
    "Laban failed to start": {
        "zh-Hans": "Laban 启动失败",
        "zh-Hant": "Laban 啟動失敗",
        "ja": "Laban の起動に失敗しました",
        "ko": "Laban을 시작하지 못했습니다",
        "fr": "Échec du démarrage de Laban",
        "es": "Laban no pudo iniciarse",
        "hi": "Laban शुरू नहीं हो सका",
        "ru": "Не удалось запустить Laban",
    },
    "Background terminal sessions failed to start": {
        "zh-Hans": "后台终端会话启动失败",
        "zh-Hant": "背景終端機工作階段啟動失敗",
        "ja": "バックグラウンドターミナルセッションの起動に失敗しました",
        "ko": "백그라운드 터미널 세션을 시작하지 못했습니다",
        "fr": "Échec du démarrage des sessions de terminal en arrière-plan",
        "es": "No se pudieron iniciar las sesiones de terminal en segundo plano",
        "hi": "पृष्ठभूमि टर्मिनल सत्र शुरू नहीं हो सके",
        "ru": "Не удалось запустить фоновые сеансы терминала",
    },
    "Use Local Sessions": {
        "zh-Hans": "使用本地会话",
        "zh-Hant": "使用本機工作階段",
        "ja": "ローカルセッションを使用",
        "ko": "로컬 세션 사용",
        "fr": "Utiliser les sessions locales",
        "es": "Usar sesiones locales",
        "hi": "स्थानीय सत्र उपयोग करें",
        "ru": "Использовать локальные сеансы",
    },
    "Restart Laban to use %@ sessions?": {
        "zh-Hans": "重新启动 Laban 以使用%@会话？",
        "zh-Hant": "重新啟動 Laban 以使用%@工作階段？",
        "ja": "%@セッションを使うには Laban を再起動しますか？",
        "ko": "%@ 세션을 사용하려면 Laban을 다시 시작할까요?",
        "fr": "Redémarrer Laban pour utiliser les sessions %@ ?",
        "es": "¿Reiniciar Laban para usar sesiones %@?",
        "hi": "%@ सत्र उपयोग करने के लिए Laban पुनः प्रारंभ करें?",
        "ru": "Перезапустить Laban для сеансов %@?",
    },
    "Existing tabs stay on the current session backend until Laban restarts.": {
        "zh-Hans": "现有标签页将保持当前会话后端，直到 Laban 重新启动。",
        "zh-Hant": "現有標籤頁將保持目前工作階段後端，直到 Laban 重新啟動。",
        "ja": "Laban を再起動するまで、既存のタブは現在のセッションバックエンドのままです。",
        "ko": "Laban을 다시 시작할 때까지 기존 탭은 현재 세션 백엔드를 유지합니다.",
        "fr": "Les onglets existants restent sur le backend de session actuel jusqu’au redémarrage de Laban.",
        "es": "Las pestañas existentes permanecen en el backend de sesión actual hasta reiniciar Laban.",
        "hi": "Laban पुनः प्रारंभ होने तक मौजूदा टैब वर्तमान सत्र बैकएंड पर रहेंगे।",
        "ru": "Существующие вкладки остаются на текущем бэкенде сеансов до перезапуска Laban.",
    },
    "Adopt": {
        "zh-Hans": "采用",
        "zh-Hant": "採用",
        "ja": "取り込む",
        "ko": "가져오기",
        "fr": "Adopter",
        "es": "Adoptar",
        "hi": "अपनाएँ",
        "ru": "Принять",
    },
    "Ignore": {
        "zh-Hans": "忽略",
        "zh-Hant": "忽略",
        "ja": "無視",
        "ko": "무시",
        "fr": "Ignorer",
        "es": "Ignorar",
        "hi": "अनदेखा करें",
        "ru": "Игнорировать",
    },
    "A background terminal session has no tab": {
        "zh-Hans": "一个后台终端会话没有标签页",
        "zh-Hant": "一個背景終端機工作階段沒有標籤頁",
        "ja": "バックグラウンドのターミナルセッションにタブがありません",
        "ko": "백그라운드 터미널 세션에 탭이 없습니다",
        "fr": "Une session de terminal en arrière-plan n’a pas d’onglet",
        "es": "Una sesión de terminal en segundo plano no tiene pestaña",
        "hi": "एक पृष्ठभूमि टर्मिनल सत्र में कोई टैब नहीं है",
        "ru": "У фонового сеанса терминала нет вкладки",
    },
    "%lld background terminal sessions have no tabs": {
        "zh-Hans": "%lld 个后台终端会话没有标签页",
        "zh-Hant": "%lld 個背景終端機工作階段沒有標籤頁",
        "ja": "%lld 個のバックグラウンドターミナルセッションにタブがありません",
        "ko": "%lld개의 백그라운드 터미널 세션에 탭이 없습니다",
        "fr": "%lld sessions de terminal en arrière-plan n’ont pas d’onglet",
        "es": "%lld sesiones de terminal en segundo plano no tienen pestañas",
        "hi": "%lld पृष्ठभूमि टर्मिनल सत्रों में कोई टैब नहीं है",
        "ru": "У %lld фоновых сеансов терминала нет вкладок",
    },
    "Laban found live shell session(s) from a previous run that aren't open in this window. Adopt them to reopen them as tabs, or ignore to leave them running in the background.": {
        "zh-Hans": "Laban 发现上次运行中仍在运行的 shell 会话未在此窗口中打开。采用它们可重新打开为标签页，忽略则继续在后台运行。",
        "zh-Hant": "Laban 發現上次執行中仍在運行的 shell 工作階段未在此視窗中開啟。採用它們可重新開啟為標籤頁，忽略則繼續在背景運行。",
        "ja": "前回の実行から存続しているシェルセッションがこのウィンドウで開かれていません。取り込むとタブとして再開し、無視するとバックグラウンドで実行を続けます。",
        "ko": "이전 실행에서 살아 있는 셸 세션이 이 창에 열려 있지 않습니다. 가져오면 탭으로 다시 열고, 무시하면 백그라운드에서 계속 실행됩니다.",
        "fr": "Laban a trouvé des sessions shell actives d’une exécution précédente qui ne sont pas ouvertes dans cette fenêtre. Adoptez-les pour les rouvrir en onglets, ou ignorez pour les laisser en arrière-plan.",
        "es": "Laban encontró sesiones de shell activas de una ejecución anterior que no están abiertas en esta ventana. Adóptalas para reabrirlas como pestañas o ignóralas para dejarlas en segundo plano.",
        "hi": "Laban ने पिछले रन से जीवित शेल सत्र पाए जो इस विंडो में खुले नहीं हैं। टैब के रूप में फिर खोलने के लिए अपनाएँ, या पृष्ठभूमि में चलने देने के लिए अनदेखा करें।",
        "ru": "Laban обнаружил активные сеансы shell с прошлого запуска, не открытые в этом окне. Примите их, чтобы открыть как вкладки, или игнорируйте, чтобы оставить в фоне.",
    },
    "Recording PTY capture": {
        "zh-Hans": "正在录制 PTY 捕获",
        "zh-Hant": "正在錄製 PTY 擷取",
        "ja": "PTY キャプチャを記録中",
        "ko": "PTY 캡처 녹화 중",
        "fr": "Enregistrement de capture PTY",
        "es": "Grabando captura PTY",
        "hi": "PTY कैप्चर रिकॉर्ड हो रहा है",
        "ru": "Запись захвата PTY",
    },
    "Capturing CPU profile": {
        "zh-Hans": "正在捕获 CPU 配置文件",
        "zh-Hant": "正在擷取 CPU 設定檔",
        "ja": "CPU プロファイルを取得中",
        "ko": "CPU 프로파일 캡처 중",
        "fr": "Capture du profil CPU",
        "es": "Capturando perfil de CPU",
        "hi": "CPU प्रोफ़ाइल कैप्चर हो रही है",
        "ru": "Снятие профиля CPU",
    },
    "Paste too large": {
        "zh-Hans": "粘贴内容过大",
        "zh-Hant": "貼上內容過大",
        "ja": "ペーストが大きすぎます",
        "ko": "붙여넣기가 너무 큽니다",
        "fr": "Collage trop volumineux",
        "es": "Pegado demasiado grande",
        "hi": "पेस्ट बहुत बड़ा है",
        "ru": "Слишком большая вставка",
    },
    "Large paste": {
        "zh-Hans": "大量粘贴",
        "zh-Hant": "大量貼上",
        "ja": "大きなペースト",
        "ko": "큰 붙여넣기",
        "fr": "Collage volumineux",
        "es": "Pegado grande",
        "hi": "बड़ा पेस्ट",
        "ru": "Большая вставка",
    },
    "About to paste %lld bytes. Continue?": {
        "zh-Hans": "即将粘贴 %lld 字节。继续？",
        "zh-Hant": "即將貼上 %lld 位元組。繼續？",
        "ja": "%lld バイトをペーストします。続行しますか？",
        "ko": "%lld바이트를 붙여넣습니다. 계속할까요?",
        "fr": "Collage de %lld octets imminent. Continuer ?",
        "es": "A punto de pegar %lld bytes. ¿Continuar?",
        "hi": "%lld बाइट पेस्ट करने वाले हैं। जारी रखें?",
        "ru": "Будет вставлено %lld байт. Продолжить?",
    },
    "Paste contains control characters or newlines": {
        "zh-Hans": "粘贴内容包含控制字符或换行符",
        "zh-Hant": "貼上內容包含控制字元或換行",
        "ja": "ペーストに制御文字または改行が含まれています",
        "ko": "붙여넣기에 제어 문자 또는 줄바꿈이 포함되어 있습니다",
        "fr": "Le collage contient des caractères de contrôle ou des sauts de ligne",
        "es": "El pegado contiene caracteres de control o saltos de línea",
        "hi": "पेस्ट में नियंत्रण वर्ण या नई पंक्तियाँ हैं",
        "ru": "Вставка содержит управляющие символы или переводы строк",
    },
    "The active program isn't using bracketed paste. Pasting may run each line as a command. Continue?": {
        "zh-Hans": "当前程序未使用括号粘贴模式。粘贴可能会将每行作为命令执行。继续？",
        "zh-Hant": "目前程式未使用括號貼上模式。貼上可能會將每行作為指令執行。繼續？",
        "ja": "アクティブなプログラムは bracketed paste を使用していません。ペーストすると各行がコマンドとして実行される可能性があります。続行しますか？",
        "ko": "활성 프로그램이 bracketed paste를 사용하지 않습니다. 붙여넣으면 각 줄이 명령으로 실행될 수 있습니다. 계속할까요?",
        "fr": "Le programme actif n’utilise pas le collage entre crochets. Coller peut exécuter chaque ligne comme une commande. Continuer ?",
        "es": "El programa activo no usa pegado entre corchetes. Pegar puede ejecutar cada línea como un comando. ¿Continuar?",
        "hi": "सक्रिय प्रोग्राम bracketed paste का उपयोग नहीं कर रहा। पेस्ट करने पर प्रत्येक पंक्ति कमांड के रूप में चल सकती है। जारी रखें?",
        "ru": "Активная программа не использует bracketed paste. Вставка может выполнить каждую строку как команду. Продолжить?",
    },
    "No active tab": {
        "zh-Hans": "没有活动标签页",
        "zh-Hant": "沒有使用中標籤頁",
        "ja": "アクティブなタブがありません",
        "ko": "활성 탭 없음",
        "fr": "Aucun onglet actif",
        "es": "No hay pestaña activa",
        "hi": "कोई सक्रिय टैब नहीं",
        "ru": "Нет активной вкладки",
    },
    "Open a tab and try again.": {
        "zh-Hans": "打开一个标签页后重试。",
        "zh-Hant": "開啟一個標籤頁後再試。",
        "ja": "タブを開いてから再試行してください。",
        "ko": "탭을 연 후 다시 시도하세요.",
        "fr": "Ouvrez un onglet et réessayez.",
        "es": "Abre una pestaña e inténtalo de nuevo.",
        "hi": "एक टैब खोलें और पुनः प्रयास करें।",
        "ru": "Откройте вкладку и повторите попытку.",
    },
    "(not installed)": {
        "zh-Hans": "（未安装）",
        "zh-Hant": "（未安裝）",
        "ja": "（未インストール）",
        "ko": "(설치되지 않음)",
        "fr": "(non installé)",
        "es": "(no instalado)",
        "hi": "(स्थापित नहीं)",
        "ru": "(не установлено)",
    },
}


def build_xcstrings() -> dict:
    strings: dict = {}
    for source, locales in TRANSLATIONS.items():
        entry: dict = {"localizations": {}}
        merged = {**locales, **SUPPLEMENT_DE_PT_IT.get(source, {})}
        for locale in LOCALES:
            value = merged.get(locale)
            if value is None:
                continue
            entry["localizations"][locale] = {
                "stringUnit": {"state": "translated", "value": value}
            }
        strings[source] = entry
    return {
        "sourceLanguage": "en",
        "strings": strings,
        "version": "1.0",
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build_xcstrings(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(TRANSLATIONS)} strings)")


if __name__ == "__main__":
    main()
